(codethorn) fixed evaluation script for parallel testing
modified:   scripts/check_consistency
modified:   scripts/runRersTimeoutTest

Added script PID ($$) to ensure when several instances of the same test
are run the files don't conflict.

CODETHORN-70

diff --git a/projects/CodeThorn/src/scripts/check_consistency b/projects/CodeThorn/src/scripts/check_consistency
--- a/projects/CodeThorn/src/scripts/check_consistency
+++ b/projects/CodeThorn/src/scripts/check_consistency
@@ -5,6 +5,16 @@
 
 # warning: the comparison is currently hard-coded to 100 properties (100 rows in the .csv file).
 
+# check that files exist
+
+if [ ! -f "$1" ]; then
+    echo "Error: $1 does not exist."
+    exit 1
+fi
+if [ ! -f "$2" ]; then
+    echo "Error: $2 does not exist."
+    exit 1
+fi
 
 # read result and solution data
 while IFS=, read pid res rest
