(codethorn) refined dead code tests
* added NODC001, NODC002
* extended evaluation script to also test for no-dead-code

CODETHORN-70

diff --git a/projects/CodeThorn/src/scripts/runDeadCodeTests b/projects/CodeThorn/src/scripts/runDeadCodeTests
--- a/projects/CodeThorn/src/scripts/runDeadCodeTests
+++ b/projects/CodeThorn/src/scripts/runDeadCodeTests
@@ -10,34 +10,19 @@ echo "------------------------------------------------"
 echo "running DEADCODE TESTS"
 echo "------------------------------------------------"
 
-BENCH_PASS=0
-BENCH_FAIL=0
-
-testNumbers1=`echo {001..008}`
-testNumbers2=`echo {009..015}`
-testNumbers="$testNumbers1 $testNumbers2"
-
-echo "Scheduled tests: $testNumbers"
-
 REPORT_DIR=test
 mkdir -p $REPORT_DIR
 
 
-function runtests {    
-for testNumber in $testNumbers; do
+function runDeadCodeTests {    
+echo "Scheduled tests: $testNumbers"
+    for testNumber in $testNumbers; do
     benchmarkprefix=$TESTDIR/${testprefix}${testNumber};
     for benchmark in ${benchmarkprefix}_*.c; do
-        rm -f tmptest.csv
-        rm -f tmptest_col1.csv
-        rm -f test${p}_col1.csv
         benchmarkname=$(basename $benchmark)
         printf "Testing %-44s : " "$benchmarkname"
         ./codethorn ${OPTIONS} --report-dir=$REPORT_DIR $benchmark > /dev/null
         dclines=`grep -v gcc_HEADERS $REPORT_DIR/dead-code-locations.csv | wc -l | cut -f1 -d' '`
-        #diff $benchmarkname.csv $TESTDIR/$benchmarkname.csv
-        #cut -d, -f1 $benchmarkname.csv | sort > $benchmarkname.line.csv
-        #cut -d, -f1 $TESTDIR/$benchmarkname.csv |sort > ${benchmarkname}_ref.line.csv
-        #diff $benchmarkname.line.csv ${benchmarkname}_ref.line.csv
         if [ ! $? -eq 0 ]
         then
 	    echo "FAIL"
@@ -49,8 +34,67 @@ for testNumber in $testNumbers; do
 done
 }
 
-testNumbers=`echo {001..015}`
-testprefix=DC
-runtests
+function runNoDeadCodeTests {    
+echo "Scheduled tests: $testNumbers"
 
-rm -rf DC*.csv
+    TESTS_FAILED=0
+    TESTS_PASSED=0
+
+    for testNumber in $testNumbers; do
+        benchmarkprefix=$TESTDIR/${testprefix}${testNumber};
+        for benchmark in ${benchmarkprefix}_*.c; do
+            benchmarkname=$(basename $benchmark)
+            printf "Testing %-44s : " "$benchmarkname"
+            ./codethorn ${OPTIONS} --report-dir=$REPORT_DIR $benchmark > /dev/null
+            dclines=`grep -v gcc_HEADERS $REPORT_DIR/dead-code-locations.csv | wc -l | cut -f1 -d' '`
+            if [ ! $? -eq 0 ]
+            then
+	        echo "FAIL"
+                exit 1
+            else
+                if [ $dclines -ne 0 ];
+                then
+	            printf "FAIL: %s unreachable locations\n" "$dclines"
+                    TESTS_FAILED=$((TESTS_FAILED+1))
+                else
+	            printf "PASS: no unreachable locations\n"
+                    TESTS_PASSED=$((TESTS_PASSED+1))
+                fi
+            fi
+        done
+    done
+    TESTS_TOTAL=$((TESTS_PASSED+TESTS_FAILED))
+    if [ $TESTS_FAILED -gt 0 ];
+    then
+        echo "$TESTS_FAILED tests of $TESTS_TOTAL failed. Exiting."
+        exit 1
+    else
+        echo "All tests passed ($TESTS_TOTAL)"
+    fi
+}
+
+ARG=$1
+
+if [[ $# -eq 0 ]];
+then
+    echo "runDeadCodeTests: usage: TESTDIR [--dc] [--no-dc]"
+    exit
+fi
+
+for arg in "$@"
+do
+    case $arg in
+        --dc)
+            testNumbers=`echo {001..015}`
+            testprefix=DC
+            runDeadCodeTests
+            ;;
+        --no-dc)
+            testNumbers=`echo {001..002}`
+            testprefix=NODC
+            runNoDeadCodeTests
+            ;;
+        *)
+            ;;
+    esac
+done
