(codethorn) extended domain tests for av-sets
CODETHORN-70

diff --git a/projects/CodeThorn/src/scripts/runDomainTests b/projects/CodeThorn/src/scripts/runDomainTests
--- a/projects/CodeThorn/src/scripts/runDomainTests
+++ b/projects/CodeThorn/src/scripts/runDomainTests
@@ -3,6 +3,10 @@
 # exit immediately with ctrl-c
 trap "exit" INT
 
+function errtrap {
+    echo "Failed with $?"
+}
+
 red=$'\e[1;31m'
 grn=$'\e[1;32m'
 yel=$'\e[1;33m'
@@ -88,12 +92,10 @@ function runDomainTestsLevel2 {
             benchmarkname=$(basename $benchmark)
             printf "Testing %-38s: " $benchmarkname
             CT_OUTPUT_FILE=$benchmarkname.imout
-            ./codethorn $benchmark $CT_MODE_OPTIONS --interpreter-mode-file=$CT_OUTPUT_FILE -I $TESTDIR > /dev/null
-            if [ ! $? -eq 0 ]
-            then
-	        echo $COLORED_FAIL
+            if ( ! ./codethorn $benchmark $CT_MODE_OPTIONS --interpreter-mode-file=$CT_OUTPUT_FILE -I $TESTDIR || fail ) &> /dev/null; then
+	        echo "$COLORED_FAIL"
                 ((numFail++))
-            else
+	    else
                 echo "$COLORED_PASS"
 		((numPass++))
             fi
@@ -109,12 +111,29 @@ CT_MODE_OPTIONS="--context-sensitive=yes --normalize-level=2 --interpreter-mode=
 echo -n "Level 3 (interpreter mode): " 
 runDomainTestsLevel3
 
+# 49,50 require abstraction mode
 testNumbers=`echo {049..050}`
 numWarnExpected=0
 numFailExpected=0
-CT_MODE_OPTIONS="--context-sensitive=yes --normalize-level=2 --interpreter-mode=0 --in-state-string-literals --exploration-mode=topologic-sort --abstraction-mode=1 --array-abstraction-index=2"
+CT_MODE_OPTIONS="--context-sensitive=yes --normalize-level=2 --interpreter-mode=0 --in-state-string-literals --exploration-mode=topologic-sort --abstraction-mode=1 --array-abstraction-index=0 --pointer-sets=off"
+echo
+echo -n "Level 2 (abstraction mode, array abstraction index=0): " 
+runDomainTestsLevel2
+
+# 49,50 require abstraction mode
+testNumbers=`echo {049..050}`
+numWarnExpected=0
+numFailExpected=0
+CT_MODE_OPTIONS="--context-sensitive=yes --normalize-level=2 --interpreter-mode=0 --in-state-string-literals --exploration-mode=topologic-sort --abstraction-mode=1 --array-abstraction-index=2 --pointer-sets=off"
 echo
 echo -n "Level 2 (abstraction mode, array abstraction index=2): " 
 runDomainTestsLevel2
 
-
+# 49,50 require abst
+testNumbers=`echo {001..050}`
+numWarnExpected=0
+numFailExpected=24
+CT_MODE_OPTIONS="--context-sensitive=yes --normalize-level=2 --interpreter-mode=0 --in-state-string-literals --exploration-mode=topologic-sort --abstraction-mode=1 --array-abstraction-index=0 --pointer-sets=on"
+echo
+echo -n "Level 2 (abstraction mode, array abstraction index=0, av-sets): " 
+runDomainTestsLevel2
