(codethorn) added option for turning report generation on/off
* new option --generate-reports=on/off
* fixed all test scripts to use name of test in addition to timestamp in tmp-dir name

CODETHORN-70

diff --git a/projects/CodeThorn/src/scripts/runRersTimeoutTest b/projects/CodeThorn/src/scripts/runRersTimeoutTest
--- a/projects/CodeThorn/src/scripts/runRersTimeoutTest
+++ b/projects/CodeThorn/src/scripts/runRersTimeoutTest
@@ -5,25 +5,31 @@
 
 SRCDIR=$1
 BUILDDIR=$2
+MAX_TIME=$3
+
+if [[ $# -ne 3 ]]; then
+    echo "Wrong number of arguments. 3 Arguments required: SRCDIR BUILDDIR MAXTIME"
+    exit 1
+fi
 
 MAKE_CHECK="_make_check"
 
 echo ".======================================================================."
-echo "| testing timeout of STG computation (5 seconds, RERS 1402, 4 threads) |"
+echo "| testing timeout of STG computation (${MAX_TIME} seconds, RERS 1402, 4 threads) |"
 echo "*======================================================================*"
 #echo "using solver 12 originally, switched to solver 5"
 
 #create a temp directory
 CURRENT_TIME=`date '+%m-%d-%y_%H:%M:%S'`
-TEMP_DIR="make_check_log_"${CURRENT_TIME}
+TEMP_DIR="make_check_log_ltlrerstimeout_"${CURRENT_TIME}
 mkdir ${2}/${TEMP_DIR}
 echo "created directory for temporary files: <CodeThorn build dir>/src/${TEMP_DIR}"
 
 #check problem specific ltl formulae/reachability of failing assertions and generate the results. Use 4 threads
-./codethorn $SRCDIR/tests/rers/Problem1402_opt.c --solver=5 --exploration-mode=loop-aware --edg:no_warnings --rersmode=yes --with-counterexamples=no --input-values="{1,2,3,4,5}" --ltl-in-alphabet="{1,2,3,4,5}" --ltl-out-alphabet="{18,19,20,21,22,23,24,25,26}" --max-time=5 --check-ltl=$SRCDIR/tests/rers/constraints-RERS14-5.txt --csv-spot-ltl="${2}/${TEMP_DIR}/Problem1402_ltl_results_maxtime_5_n_la${MAKE_CHECK}.csv" --csv-assert="${2}/${TEMP_DIR}/Problem1402_assert_results_maxtime_5_n_la${MAKE_CHECK}.csv" --threads=4 --status
+./codethorn $SRCDIR/tests/rers/Problem1402_opt.c --solver=5 --exploration-mode=loop-aware --edg:no_warnings --rersmode=yes --with-counterexamples=no --input-values="{1,2,3,4,5}" --ltl-in-alphabet="{1,2,3,4,5}" --ltl-out-alphabet="{18,19,20,21,22,23,24,25,26}" --max-time=$MAX_TIME --check-ltl=$SRCDIR/tests/rers/constraints-RERS14-5.txt --csv-spot-ltl="${2}/${TEMP_DIR}/Problem1402_ltl_results_maxtime_${MAX_TIME}_n_la${MAKE_CHECK}.csv" --csv-assert="${2}/${TEMP_DIR}/Problem1402_assert_results_maxtime_${MAX_TIME}_n_la${MAKE_CHECK}.csv" --threads=4 --status
 
 #compare with regression data
-$SRCDIR/scripts/check_consistency ${2}/${TEMP_DIR}/Problem1402_ltl_results_maxtime_5_n_la${MAKE_CHECK}.csv $SRCDIR/regressiondata2/Problem1402_ltl_solutions.csv 2>&1
+$SRCDIR/scripts/check_consistency ${2}/${TEMP_DIR}/Problem1402_ltl_results_maxtime_${MAX_TIME}_n_la${MAKE_CHECK}.csv $SRCDIR/regressiondata2/Problem1402_ltl_solutions.csv 2>&1
 if [ ! $? -eq 0 ] 
 then 
   echo "ERROR: RERS LTL regression data could not be correctly reproduced."
@@ -33,7 +39,7 @@ else
   echo "Success: all results for verified/falsified properties are correct."
 fi
 
-$SRCDIR/scripts/check_consistency ${2}/${TEMP_DIR}/Problem1402_assert_results_maxtime_5_n_la${MAKE_CHECK}.csv $SRCDIR/regressiondata2/Problem1402_reachability_solutions.csv 2>&1
+$SRCDIR/scripts/check_consistency ${2}/${TEMP_DIR}/Problem1402_assert_results_maxtime_${MAX_TIME}_n_la${MAKE_CHECK}.csv $SRCDIR/regressiondata2/Problem1402_reachability_solutions.csv 2>&1
 if [ ! $? -eq 0 ] 
 then 
   echo "ERROR: RERS reachability regression data could not be correctly reproduced."
@@ -48,6 +54,6 @@ rm -rf ${2}/${TEMP_DIR}
 echo "removed directory for temporary files: <CodeThorn build dir>/src/${TEMP_DIR}"
     
 echo ".==============================================================================."
-echo "| STG computation timeout tested succesfully (5 seconds, RERS 1402, 4 threads) |"
+echo "| STG computation timeout tested succesfully (${MAX_TIME} seconds, RERS 1402, 4 threads) |"
 echo "*==============================================================================*"
 
