CT: extended expr-eval with conditional operator evaluating to top.

diff --git a/projects/CodeThorn/src/scripts/verify_polybench b/projects/CodeThorn/src/scripts/verify_polybench
--- a/projects/CodeThorn/src/scripts/verify_polybench
+++ b/projects/CodeThorn/src/scripts/verify_polybench
@@ -1,32 +1,39 @@
 #!/bin/bash 
 
 # Author: Markus Schordan, 2014.
-
 # this file assumes codethorn to be available in PATH.
 
-CODETHORN=/export/tmp.schordan1/development/rosework/mainbranch/compiletree/projects/CodeThorn/src/codethorn
-MYBENCHPATH="./"
+MYBENCHPATH="."
+CODETHORN=codethorn
+
+all_benchmarks="2mm 3mm adi atax bicg cholesky correlation covariance durbin fdtd-2d floyd-warshall gemm gemver gesummv gramschmidt jacobi-1d-imper jacobi-2d-imper ludcmp lu mvt reg_detect seidel-2d symm syr2k syrk trisolv trmm"
+all_longbenchmarks="fdtd-apml doitgen"
+some_variants="fuse_nofuse fuse_smartfuse tile_1_5_1 tile_5_16_1 tile_8_16_1"
+all_variants=`ls jacobi-1d-imper_mod_*.c | sed 's/jacobi-1d-imper_mod_//g'| sed 's/\.c//g'`
 
 function check {
 dirname=$1 # directory where to test
 origtestresult=$2 # result file
 fullbenchname=$3 # name of program
-#echo "DEBUG:dirname $dirname"
-#echo "DEBUG:origtestresult $origtestresult"
-#echo "DEBUG:fullbenchname $fullbenchname"
 onlybenchname=`basename "$fullbenchname"`
 
-echo -n "checking variant: ${onlybenchname}.c: " 
+#echo -n "checking variant  : ${onlybenchname}.c: " 
+printf "checking variant  : %-40s: " "$onlybenchname.c"
+
 if [ -e ${fullbenchname}.c ]; then
-  ${CODETHORN} ${fullbenchname}.c -I${dirname} -DARRAYSIZE=16 -DSTEPSIZE=2 --threads=6 --edg:no_warnings --dump-sorted=${fullbenchname}.check --dump-non-sorted=${fullbenchname}.nscheck --csv-stats=${fullbenchname}.stats #>& /dev/null
-#  cp arrayupdates.txt ${fullbenchname}.check
-  if(diff ${origtestresult} ${fullbenchname}.check >& /dev/null); then
-  echo "PASS" > ${fullbenchname}.verify
-  cat ${fullbenchname}.verify
+  if(${CODETHORN} ${fullbenchname}.c -I${dirname} -DARRAYSIZE=16 -DSTEPSIZE=2 -DGRIDSIZE=16 --threads=6 --edg:no_warnings --dump-sorted=${fullbenchname}.check --dump-non-sorted=${fullbenchname}.nscheck --csv-stats=${fullbenchname}.stats >& /dev/null); then
+    if(diff ${origtestresult} ${fullbenchname}.check >& /dev/null); then
+      echo "PASS" > ${fullbenchname}.verify
+      cat ${fullbenchname}.verify
+    else
+      echo "FAIL" > ${fullbenchname}.verify
+      cat ${fullbenchname}.verify
+    fi
   else
-  echo "FAIL" > ${fullbenchname}.verify
-  cat ${fullbenchname}.verify
+    echo "ERROR" > ${fullbenchname}.verify
+    cat ${fullbenchname}.verify
   fi
+
 else
   echo "SKIP (does not exist)"
   # generate empty stats file
@@ -36,100 +43,78 @@ else
 fi
 }
 
-#for k in tests/polyhedralTest-size16-tilesize16/stencils ; do
-#  if [ -d "$k" ]; then
-#    echo "-------------------------"
-#    echo "CHECKING $k"
-#    for i in ${k}/* ; do
-
 function check_benchmark {
   i=$1 # directory path
   benchname=$2
       if [ -f "${i}/${benchname}_mod.c" ]; then
-        echo "Checking: ${benchname}"
-
+        echo "------------------------------------------------------------------"
+        printf "Checking: %-40s          ------\n" ${benchname}
+        echo "------------------------------------------------------------------"
         # create mod-benchmark result
-        echo "analyzing: ${benchname}_mod.c"
-        ${CODETHORN} ${i}/${benchname}_mod.c -I${i} -DARRAYSIZE=16 -DSTEPSIZE=2 --threads=6 --edg:no_warnings --dump-sorted=${i}/${benchname}_mod.check --dump-non-sorted=${i}/${benchname}_mod.nscheck --csv-stats=${i}/${benchname}_mod.stats #>& /dev/null
-#        cp arrayupdates.txt ${i}/${benchname}.check
+        printf "analyzing original: %-40s: " "${benchname}_mod.c"
+        ${CODETHORN} ${i}/${benchname}_mod.c -I${i} -DARRAYSIZE=16 -DSTEPSIZE=2 -DGRIDSIZE=16 --threads=6 --edg:no_warnings --dump-sorted=${i}/${benchname}_mod.check --dump-non-sorted=${i}/${benchname}_mod.nscheck --csv-stats=${i}/${benchname}_mod.stats #& /dev/null
+		printf "DONE\n"
 
         # check with variants
-        check "${i}" "${i}/${benchname}_mod.check" "${i}/${benchname}_mod_fuse_nofuse"
-        check "${i}" "${i}/${benchname}_mod.check" "${i}/${benchname}_mod_fuse_smartfuse"
-        check "${i}" "${i}/${benchname}_mod.check" "${i}/${benchname}_mod_tile_1_5_1"
+		for variant in $some_variants; do
+          check "${i}" "${i}/${benchname}_mod.check" "${i}/${benchname}_mod_${variant}"
+        done
       else
-        echo "Error2: "${i}/${benchname}_mod.c" does not exit."
+        echo "Error 2: ${i}/${benchname}_mod.c does not exit."
         exit
       fi
 }
 
-# failing because of function call
-failing="datamining/correlation"
-
-allbenchmarks="stencils/jacobi-1d-imper stencils/jacobi-2d-imper stencils/seidel-2d linear-algebra/kernels/2mm linear-algebra/kernels/3mm linear-algebra/kernels/atax linear-algebra/kernels/bicg linear-algebra/kernels/cholesky linear-algebra/kernels/doitgen linear-algebra/kernels/gemm linear-algebra/kernels/gemver linear-algebra/kernels/gesummv linear-algebra/kernels/mvt linear-algebra/kernels/symm linear-algebra/kernels/syr2k linear-algebra/kernels/syrk linear-algebra/kernels/trisolv linear-algebra/kernels/trmm linear-algebra/solvers/durbin linear-algebra/solvers/dynprog linear-algebra/solvers/gramschmidt linear-algebra/solvers/lu linear-algebra/solvers/ludcmp datamining/correlation datamining/covariance stencils/adi stencils/fdtd-2d stencils/fdtd-apml"
-
-allbenchmarks_new="2mm 3mm adi atax bicg cholesky correlation covariance durbin fdtd-2d fdtd-apml floyd-warshall gemm gemver gesummv gramschmidt jacobi-1d-imper jacobi-2d-imper ludcmp lu mvt reg_detect seidel-2d symm syr2k syrk trisolv trmm"
-
 function runallgeneralbenchmarks_param {
-selectedbenchmarks="$1"
-# all benchmarks for 3 above cases
-
-for mybench in ${selectedbenchmarks}; do
-  check_benchmark ${MYBENCHPATH} ${mybench}
-done
+  selectedbenchmarks="$1"
+  for mybench in ${selectedbenchmarks}; do
+    check_benchmark ${MYBENCHPATH} ${mybench}
+  done
 }
 
 function runallgeneralbenchmarks {
 # all benchmarks for 3 above cases
 for mybenchpath in polybench_variants; do
-for mybench in ${allbenchmarks_new}; do
+for mybench in ${all_benchmarks}; do
   check_benchmark $MYBENCHPATH ${mybench}
 done
 done
 }
 
-function runallcornercases {
-# all corner cases
-for mybenchpath in polyhedralTest-size16-tilesize16 polyhedralTest-size16-tilesizePrime polyhedralTest-size16-Largetilesize polyhedralTest-size16-maxfuse polyhedralTest-size16-nofuse polyhedralTest-size16-smartfuse polyhedralTest-size16-tilesize1 polyhedralTest-size16-tilesize16 polyhedralTest-size16-tilesizePrime polyhedralTest-size16-tilesizePrime2; do
-for mybench in "stencils/jacobi-2d-imper" "linear-algebra/kernels/cholesky" "datamining/covariance"; do
-  FULLNAME=${mypath}/${mybenchpath}/${mybench}
-  check_benchmark $FULLNAME
-done
-done
-}
+hash $CODETHORN 2>/dev/null || { echo >&2 "The program codethorn is required but it's not installed. Aborting."; exit 1; }
 
-if [ "$#" -ne 1 ]; then
-    echo "Usage: polycheck_all --check1 | --check2 | --par | --seq"
+if [ "$#" -eq 0 ]; then
+    echo "Usage: verify_polybench --checkallmedium | --checklong1 | --checklong2 | --checkfuncalls | --checkfast | --check <benchmark> --list"
     exit
 fi
    case "$1" in
-        --check1) runallgeneralbenchmarks
+        --checkallmedium) runallgeneralbenchmarks
             ;;
-        --check2) runallcornercases
-            ;;
-        --par) runallgeneralbenchmarks &
-               runallcornercases &
-            ;;
-        --seq)
-               runallgeneralbenchmarks
-               runallcornercases
-            ;;
-	    --longcheck1)
+	    --checklong1)
                runallgeneralbenchmarks_param "fdtd-apml"
             ;;
-	    --longcheck2)
+	    --checklong2)
                runallgeneralbenchmarks_param "doitgen"
             ;;
-       --funcallcheck)
+       --checkfuncalls)
            # cond-operator: cholesky, correlation
            # function call only: gramschmidt
-           runallgeneralbenchmarks_param "cholesky correlation gramschmidt"
+           runallgeneralbenchmarks_param "cholesky correlation gramschmidt floyd-warshall"
            ;;
-       --fastcheck)
-           runallgeneralbenchmarks_param "atax covariance jacobi-1d-imper jacobi-2d-imper"
+       --checkproblematic)
+           # cond-operator: cholesky, correlation
+           # function call only: gramschmidt
+           runallgeneralbenchmarks_param "reg_detect cholesky"
            ;;
-
-
+       --checkfast)
+           runallgeneralbenchmarks_param "atax jacobi-1d-imper"
+           ;;
+       --check)
+           runallgeneralbenchmarks_param "$2"
+		   ;;
+	   --list)
+           echo $all_benchmarks $all_longbenchmarks
+		   ;;
 
         --*) echo "bad option $1"
             ;;
