More scripting for automated releasing the git master branch

diff --git a/scripts/hudson/importRoseGitDistributionToSVN b/scripts/hudson/importRoseGitDistributionToSVN
--- a/scripts/hudson/importRoseGitDistributionToSVN
+++ b/scripts/hudson/importRoseGitDistributionToSVN
@@ -34,24 +34,56 @@ fi
 # remove previous left over temporary dir generated by svn_load_dirs.??.pl
 rm -rf /tmp/svn_load_dirs*
 
+# obtain and test the input parameters
 ROSE_SOURCE_PATH=$1
 ROSE_BUILD_PATH=$2
+if [ -d ${ROSE_SOURCE_PATH} ]; then
+  if [ -f ${ROSE_SOURCE_PATH}/rose_config.h.in ] ;
+   then
+     echo ${ROSE_SOURCE_PATH} is verified to be a rose source tree
+   else
+     echo Fatal error: ${ROSE_SOURCE_PATH} does not seem to be a rose source tree!
+     exit 3
+  fi
+else  
+  echo Fatal error: ${ROSE_SOURCE_PATH} does not exist!
+  exit 3
+fi
+
+if [ -d ${ROSE_BUILD_PATH} ]; then
+  if [ -f ${ROSE_BUILD_PATH}/rose_config.h ] ;
+   then
+     echo ${ROSE_BUILD_PATH} is verified to be a rose build tree
+   else
+     echo Fatal error: ${ROSE_BUILD_PATH} does not seem to be a rose build tree!
+     exit 3
+  fi
+else  
+  echo Fatal error: ${ROSE_BUILD_PATH} does not exist!
+  exit 3
+fi
+
+
 cd ${ROSE_BUILD_PATH}
 
 # we now have a different name scheme
 # set max depth to avoid finding 
 # src/frontend/CxxFrontend/roseBinaryEDG-x86_64-pc-linux-gnu-GNU-4.2-14fb2b019a16bb36f47609dad91a1807.tar.gz
 ROSE_DISTRIBUTION=$(find . -maxdepth 1  -name  rose\*.tar.gz)
+
 if [ $? -ne 0 ]; then
    echo "Fatal error: cannot find the distribution package!"
    exit 1
 fi
 
 # double check here!! Liao, 9/25/2009
-if [ "x$ROSE_DISTRIBUTION" = "x" ]; then
-   echo "Fatal error: cannot find the distribution package!"
-   exit 1
-fi
+
+# this will be caught by the error code of tar
+#ROSE_DISTRIBUTION_2=`echo $ROSE_DISTRIBUTION | cut -f 3 -d \ `
+#if [ "x$ROSE_DISTRIBUTION_2" != "x" ]; then
+#    echo "Fatal error Found more than one rose distribution packages!! $ROSE_DISTRIBUTION"
+#    exit 3
+#fi
 
 echo Found the ROSE distribution package: $ROSE_DISTRIBUTION
 
@@ -66,6 +98,10 @@ mkdir -p ${UPLOAD_DIR}
 # unpack the package to the work dir and get the root dir of the distribution
 #----------------------------------------------------
 tar xzvf ${ROSE_DISTRIBUTION} -C ${UPLOAD_DIR}
+if [ $? -ne 0 ]; then
+   echo "Fatal error for: tar xzvf ${ROSE_DISTRIBUTION} -C ${UPLOAD_DIR}"
+   exit 1
+fi
 
 cd ${UPLOAD_DIR}
 ROSE_DIST_DIR=$(ls ${UPLOAD_DIR})
