Debugging ROSE compiling ROSE.

diff --git a/scripts/hudson/runHudsonRoseCompileRoseTest b/scripts/hudson/runHudsonRoseCompileRoseTest
--- a/scripts/hudson/runHudsonRoseCompileRoseTest
+++ b/scripts/hudson/runHudsonRoseCompileRoseTest
@@ -192,7 +192,8 @@ echo "**************************************************************************
 echo "Done with make check step"
 
 echo "Starting make install step (so we can save a installed copy for secondary tests)"
-make -j8 install
+# make -j8 install
+sleep 5
 echo "Done with make install step (so we can save a installed copy for secondary tests)"
 
 end_time_make_distcheck_seconds="$(date +%s)"
@@ -218,3 +219,6 @@ echo ""
 echo "********************************************************************"
 echo "Executed runTest for ROSE Project on: $machine_name date = $end_date"
 echo "********************************************************************"
+
+echo "Ending in an error since this script is not finished yet..."
+exit 1
