Debugging ROSE compiling ROSE Hudson script.

diff --git a/scripts/hudson/runHudsonRoseCompileRoseTest b/scripts/hudson/runHudsonRoseCompileRoseTest
--- a/scripts/hudson/runHudsonRoseCompileRoseTest
+++ b/scripts/hudson/runHudsonRoseCompileRoseTest
@@ -228,6 +228,9 @@ ls -l ${CONFIGURE_PREFIX_DIR}/bin/testAnalysis
 echo "Put testAnalysis is in the default path."
 export PATH="${CONFIGURE_PREFIX_DIR}/bin:$PATH"
 
+echo "Put boost libs into LD_LIBRARY_PATH."
+export LD_LIBRARY_PATH="/home/hudson-rose/tmp/opt/boost_1_37_0.gxx-4.2.4/lib:$LD_LIBRARY_PATH"
+
 echo "Make sure that testAnalysis is in the default path."
 which testAnalysis
 
@@ -278,5 +281,5 @@ echo "********************************************************************"
 echo "Executed runTest for ROSE Project on: $machine_name date = $end_date"
 echo "********************************************************************"
 
-echo "Ending in an error since this script is not finished yet..."
-exit 1
+# echo "Ending in an error since this script is not finished yet..."
+# exit 1
