Fixed ROSE-Insure++ build tree path.

diff --git a/scripts/hudson/runInsureOnRose b/scripts/hudson/runInsureOnRose
--- a/scripts/hudson/runInsureOnRose
+++ b/scripts/hudson/runInsureOnRose
@@ -305,16 +305,18 @@ case "$ROSE_TEST_BUILD_STEP" in
 
 "analyze")
 
-    ssh hudson-rose@hudson-rose-23 test -d /export/tmp.hudson-rose/hudson/workspace/test-insure-build/ROSE-build;
+    set +e
+    ssh hudson-rose@hudson-rose-23 test -d /export/tmp.hudson-rose/hudson/workspace/test-insure-build/ROSE_TEST_BUILD_STEP/build/ROSE_TEST_GCC_VERSION/4.2.4/label/hudson-rose-23/ROSE-build; 
     if [ $? -ne 0 ] ; then
-	echo "Error: no build tree found at hudson-rose@hudson-rose-23:/export/tmp.hudson-rose/hudson/workspace/test-insure-build/ROSE-build"
+	echo "Error: no build tree found at hudson-rose@hudson-rose-23:/export/tmp.hudson-rose/hudson/workspace/test-insure-build/ROSE_TEST_BUILD_STEP/build/ROSE_TEST_GCC_VERSION/4.2.4/label/hudson-rose-23/ROSE-build"
 	exit 1
     fi
+    set -e
 
     # TOO (4/23/2011): Use the same Insure++ ROSE build tree that was created during test-insure-build
     # TODO: use rsync instead to make it faster
     rm -rf ROSE-build
-    scp -r hudson-rose@hudson-rose-23:/export/tmp.hudson-rose/hudson/workspace/test-insure-build/ROSE-build .
+    scp -r hudson-rose@hudson-rose-23:/export/tmp.hudson-rose/hudson/workspace/test-insure-build/ROSE_TEST_BUILD_STEP/build/ROSE_TEST_GCC_VERSION/4.2.4/label/hudson-rose-23/ROSE-build .
 
     cd ROSE-build
 
