Minor fix to Insure++ Hudson script.

diff --git a/scripts/hudson/runInsureOnRose b/scripts/hudson/runInsureOnRose
--- a/scripts/hudson/runInsureOnRose
+++ b/scripts/hudson/runInsureOnRose
@@ -52,10 +52,10 @@ if test "x$ROSE_TEST_BUILD_STEP" = "xanalyze" ; then
     echo "Error: you did not specify a 'ROSE_INSURE_BUILD_TREE' for analysis = '${ROSE_INSURE_BUILD_TREE}'"
     exit 1
   fi
-  if test ! -d "${ROSE_INSURE_BUILD_TREE}" ; then
-    echo "Error: '${ROSE_INSURE_BUILD_TREE}' does not seem to be a valid ROSE_INSURE_BUILD_TREE for analysis"
-    exit 1
-  fi
+#  if test ! -d "${ROSE_INSURE_BUILD_TREE}" ; then
+#    echo "Error: '${ROSE_INSURE_BUILD_TREE}' does not seem to be a valid ROSE_INSURE_BUILD_TREE for analysis"
+#    exit 1
+#  fi
 fi
 
 
