Added additional logic for copying the ROSE-Insure++ build tree to another node for performing the Insure++ analysis step.

diff --git a/scripts/hudson/runInsureOnRose b/scripts/hudson/runInsureOnRose
--- a/scripts/hudson/runInsureOnRose
+++ b/scripts/hudson/runInsureOnRose
@@ -305,6 +305,7 @@ case "$ROSE_TEST_BUILD_STEP" in
 
 "analyze")
 
+    # Make sure the ROSE-Insure++ build tree exists
     set +e
     ssh hudson-rose@hudson-rose-23 test -d ${ROSE_INSURE_BUILD_TREE}
     if [ $? -ne 0 ] ; then
@@ -315,8 +316,24 @@ case "$ROSE_TEST_BUILD_STEP" in
 
     # TOO (4/23/2011): Use the same Insure++ ROSE build tree that was created during test-insure-build
     # TODO: use rsync instead to make it faster
+    # TODO: if test-insure-build is run again, the build tree won't be valid since scp would be corrupt.
     rm -rf ROSE-build
-    scp -r hudson-rose@hudson-rose-23:${ROSE_INSURE_BUILD_TREE} .
+    
+    # We need to copy the ROSE-Insure++ build tree to the other analysis node
+    if test "x$machine_name" = "xhudson-rose-20" ; then
+      buildTree=`echo $ROSE_INSURE_BUILD_TREE | sed 's/hudson-rose-23/hudson-rose-20/;s/ROSE-build//'`
+      echo "buildTree = $buildTree"
+      if test "x$buildTree" = "x" -o "x$buildTree" = "x\/" ; then
+        echo "buildTree is invalid and could cause problems when issuing 'rm -rf' on it"
+        exit 1
+      fi
+      rm -rf ${buildTree}/*
+      scp -r hudson-rose@hudson-rose-23:${ROSE_INSURE_BUILD_TREE} ${buildTree}
+      cd ${buildTree}
+      find . -type f -print0 | xargs -0 sed -i "s/hudson-rose-23/hudson-rose-20/g"
+    else
+      scp -r hudson-rose@hudson-rose-23:${ROSE_INSURE_BUILD_TREE} .
+    fi
 
     cd ROSE-build
 
