Add debug statement to Klocwork.

diff --git a/scripts/hudson/runKlocworkOnRose b/scripts/hudson/runKlocworkOnRose
--- a/scripts/hudson/runKlocworkOnRose
+++ b/scripts/hudson/runKlocworkOnRose
@@ -324,8 +324,9 @@ printBannerToEndStep "configure" $configure_start_time
     # rose:build_XXXX
     HEAD_HASH=`git rev-parse HEAD`
     kwadmin load rose tables --name $HEAD_HASH
-    if [ ${PIPESTATUS[0]} -ne 0 -o $? -ne 0 ]  ; then
-       printBanner "Fatal error during 'kwadmin load rose tables --name $HEAD_HASH'. Aborting..."
+    status="$?"
+    if [ "$status" -ne 0 ]  ; then
+       printBanner "Fatal error (${status}) during 'kwadmin load rose tables --name $HEAD_HASH'. Aborting..."
        exit 3
     fi
 
