Set the output of make-full environment variables to be conditional.

diff --git a/scripts/hudson/runParallelizedTest-with-osx b/scripts/hudson/runParallelizedTest-with-osx
--- a/scripts/hudson/runParallelizedTest-with-osx
+++ b/scripts/hudson/runParallelizedTest-with-osx
@@ -36,11 +36,14 @@ echo "ROSE_TEST_BUILD_STYLE             = ${ROSE_TEST_BUILD_STYLE}"             
 echo "ROSE_TEST_BOOST_PATH              = ${ROSE_TEST_BOOST_PATH}"               >> $env_dump_file
 echo "ROSE_TEST_JAVA_PATH               = ${ROSE_TEST_JAVA_PATH}"                >> $env_dump_file
 
-echo "Environment variables required for ROSE_TEST_BUILD_STYLE = full"           >> $env_dump_file
-echo "ROSE_TEST_QT_PATH                 = ${ROSE_TEST_QT_PATH}"                  >> $env_dump_file
-echo "ROSE_TEST_SQLITE_PATH             = ${ROSE_TEST_SQLITE_PATH}"              >> $env_dump_file
-echo "ROSE_TEST_RTED_PATH               = ${ROSE_TEST_RTED_PATH}"                >> $env_dump_file
-echo "ROSE_TEST_OPENGL_PATH             = ${ROSE_TEST_OPENGL_PATH}"              >> $env_dump_file
+echo "$ROSE_TEST_BUILD_STYLE" | grep --quiet "make.*full"
+if test $? = 0 ; then
+ echo "Environment variables required for ROSE_TEST_BUILD_STYLE = full"           >> $env_dump_file
+ echo "ROSE_TEST_QT_PATH                 = ${ROSE_TEST_QT_PATH}"                  >> $env_dump_file
+ echo "ROSE_TEST_SQLITE_PATH             = ${ROSE_TEST_SQLITE_PATH}"              >> $env_dump_file
+ echo "ROSE_TEST_RTED_PATH               = ${ROSE_TEST_RTED_PATH}"                >> $env_dump_file
+ echo "ROSE_TEST_OPENGL_PATH             = ${ROSE_TEST_OPENGL_PATH}"              >> $env_dump_file
+fi
 
 echo "-------------------------------------------------------------------"       >> $env_dump_file
 if test "x$label" = "x64bit-macos-10.6" ; then
