Added Mac OS X 10.6 test to hudson test script.

diff --git a/scripts/hudson/runParallelizedTest-with-osx b/scripts/hudson/runParallelizedTest-with-osx
--- a/scripts/hudson/runParallelizedTest-with-osx
+++ b/scripts/hudson/runParallelizedTest-with-osx
@@ -305,7 +305,7 @@ echo ""                                                                         
 echo ""                                                                          >> $env_dump_file
 
 echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"       >> $env_dump_file
-echo "                        Test Environment"                                  >> $env_dump_file
+echo "                        Test-environment"                                  >> $env_dump_file
 echo "*******************************************************************"       >> $env_dump_file
 echo ""                                                                          >> $env_dump_file
 echo ""                                                                          >> $env_dump_file
@@ -313,8 +313,6 @@ echo ""                                                                         
 echo ""                                                                          >> $env_dump_file
 
 cat $env_dump_file
-
-exit 0;
 
 #########################################################################################
 #
@@ -376,43 +374,61 @@ else
 fi
 
 
-if test -e ROSE-install ; then chmod -R u+xw ROSE-install ; fi
+if test -e ROSE-install ; then 
+  chmod -R u+xw ROSE-install
+fi
 rm -rf ROSE-install
 
-
-if test -e ROSE-build ; then chmod -R u+wx ROSE-build ; fi
+if test -e ROSE-build ; then
+  chmod -R u+wx ROSE-build
+fi
 rm -rf ROSE-build
 mkdir ROSE-build
 cd ROSE-build
-echo "Starting configure step"
-# ../configure ${CONFIGURE_FLAGS}
-../configure --prefix=${CONFIGURE_PREFIX_DIR} ${CONFIGURE_FLAGS}
-echo "Done with configure step"
 
-if test $ROSE_TEST_BUILD_STYLE = edg ; then
- # DQ (10/19/2010): This is confusing syntax, NUM_PROCESS is a shell variable set in Hudson where this script is called.
- # make -j${NUM_PROCESS:-$def_num_procs} upload_edg_binary && make -Csrc/frontend/CxxFrontend deploy_tarballs
-   make -j${NUM_PROCESS} upload_edg_binary && make -Csrc/frontend/CxxFrontend deploy_tarballs
-      if [ $? -ne 0 ]  ; then
-        echo "fatal error when build edg binaries , aborting..."
-        # tps : call this line before any exit. It resets the Windows test
-        #echo 3 > $win_file
-        exit 3
-      fi
+#########################################################################################
+#
+#  Mac OS X 10.6 
+#
+#########################################################################################
+if test "x$label" = "x64bit-macos-10.6" ; then
+  ../configure --prefix=${CONFIGURE_PREFIX_DIR} --with-boost=${ROSE_TEST_BOOST_PATH} --with-boost-lib={$ROSE_TEST_BOOST_PATH}/lib/ --with-CXX_DEBUG=-g --with-CXX_WARNINGS=-Wall
 
-	exit 0
+  time make -j8
+  if [ $? -ne 0 ]  ; then
+    echo "Fatal error in Mac OS X 10.6 build step: make. Aborting..."
+    exit 3
+  fi
+  time make check -j8
+  if [ $? -ne 0 ]  ; then
+    echo "Fatal error in Mac OS X 10.6 build step: make check. Aborting..."
+    exit 3
+  else
+    exit 0
+  fi
 fi
 
-# Provide a disk usage report to support debugging when Hudson has a problem.
-# echo "Disk usage report #3 (to support debugging when Hudson has a problem):"
-# df /export
+#########################################################################################
+#
+#  ROSE/configure
+#
+#########################################################################################
+TMPFILE=/tmp/hudson_${hudson_start_time_seconds}
+echo "*******************************************************************"       >> $TMPFILE
+echo "                     Starting configure step..."                           >> $TMPFILE
+echo "-------------------------------------------------------------------"       >> $TMPFILE
+cat $TMPFILE
+rm -rf $TMPFILE
+#########################################################################################
+../configure --prefix=${CONFIGURE_PREFIX_DIR} ${CONFIGURE_FLAGS}
+#########################################################################################
+echo "*******************************************************************"       >> $TMPFILE
+echo "                     Done with configure step..."                          >> $TMPFILE
+echo "-------------------------------------------------------------------"       >> $TMPFILE
+cat $TMPFILE
+rm -rf $TMPFILE
 
-# Andreas suggests that the use of "tee" is not passing error through to Hudson.
-# DQ has confirmed that Andreas's point is true for bash but false for tcsh 
-# (where it was originally tested).
-echo "Starting compile step"
 
-start_time_make_seconds="$(date +%s)"
 
 # TOO (2/24/2011): Requires librose.la
 function printRoseTranslatorVersion {
@@ -421,10 +437,14 @@ function printRoseTranslatorVersion {
     make PrintRoseTranslatorVersion
 }
 
-####################################################################################
-# if test false; then
-ROSE_SPEW_ANALYSIS=yes
 
+#########################################################################################
+#
+#  ROSE/make
+#
+#########################################################################################
+start_time_make_seconds="$(date +%s)"
+ROSE_SPEW_ANALYSIS=yes
 
 case "$ROSE_TEST_BUILD_STYLE" in
 "make/check/install-minimal"|"make/check/install-full")
@@ -513,5 +533,5 @@ echo "**************************************************************************
 end_date=`date`
 echo ""
 echo "********************************************************************"
-echo "Executed runParallelizedTest (" ${ROSE_TEST_BUILD_STYLE} ")  for ROSE Project on: $machine_name date = $end_date"
+echo "Executed runParallelizedTest-with-osx (" ${ROSE_TEST_BUILD_STYLE} ")  for ROSE Project on: $machine_name date = $end_date"
 echo "********************************************************************"
