Added WINDOWS test to ROSE-matrix job. Tested on opengl job - so fingers crossed.

diff --git a/scripts/hudson/runTest b/scripts/hudson/runTest
--- a/scripts/hudson/runTest
+++ b/scripts/hudson/runTest
@@ -23,6 +23,46 @@ echo "ROSE_TEST_RTED_PATH               = ${ROSE_TEST_RTED_PATH}"
 echo "ROSE_TEST_OPENGL_PATH             = ${ROSE_TEST_OPENGL_PATH}"
 echo "*******************************************************************"
 
+# *********************************************************************
+# WINDOWS SPECIFIC CODE: tps 07/14/2010. Second part at end of file
+# Before we start k hudson jobs, we check for a file in nfs/casc/..../ROSE/git
+# if the file does not exist we create it with a value > 0
+# If the file contains any value > 0 we start the Windows test and set the value to 0
+# Otherwise we do not start the Windows test. In this way the Windows test is started once.
+# 
+# At the end of the file we check the return value from Windows.
+# Only if the return value is 1 then Windows has passed with success.
+# To make sure that only the job starting WINDOWS is checkinng for the return value
+# we use the variable jobstartingwin to check.
+# 
+export win_file=/nfs/casc/overture/ROSE/git/rose_win_test.rose
+echo "Testing weather Windows test has started. Start only once!"
+jobstartingwin=0
+if [ -e $win_file ]
+then
+    echo "Found file $win_file"
+else
+    echo "Creating $win_file"
+    echo 5 > $win_file
+fi
+
+cat ${win_file} | \
+while read -a num 
+do
+if [ "${num[0]}" == "0" ]; then
+    echo "Windows test has already started."
+else
+    echo 0 > $win_file
+    jobstartingwin=1
+    echo "Starting Windows test."
+#starting Windows process
+    curl http://tux269.llnl.gov:8080/job/ROSE-Windows-from-scratch/build?token=WIN
+fi
+done
+#
+# *********************************************************************
+
+
 # Output the name of the machine where the build is being run (helpful for debugging).
 machine_name=`uname -n`
 start_time=`date`
@@ -419,6 +459,42 @@ echo "**************************************************************************
 #echo "**************************************************************************************************"
 #echo "Executing runTest for ROSE Project on: $machine_name start_time = $start_time end_time = $end_time"
 #echo "**************************************************************************************************"
+
+# **************************************************************
+# WINDOWS PART2: THIS SHOULD BE AT THE END OF THE FILE
+# Check Windows return value. See more explanation in top of file
+if [ $jobstartingwin -eq 1 ] 
+then
+echo "Testing result of Windows Hudson Test..."
+if [ -e $win_file ]
+then
+    echo "Found file $win_file"
+else
+    echo "File not found $win_file"
+    exit 3
+fi
+
+cat ${win_file} | \
+while read -a num 
+do
+if [ "${num[0]}" == "1" ]; then
+echo "Windows has passed the recent Hudson test"
+else
+echo "Windows has failed the recent Hudson test."
+echo "Please check the Windows Hudson test for its output to"
+echo "determine the exact error"
+exit 3
+fi
+done
+
+echo "Done testing."
+fi 
+# **************************************************************
+
+
+
+
+
 
 # DQ (2/12/2010): Added the ROSE version number to the base of the output
 echo "Version numbers of ROSE and the different parts of ROSE."
