Debugging Hudsome problem on tux269.

diff --git a/scripts/hudson/runTest b/scripts/hudson/runTest
--- a/scripts/hudson/runTest
+++ b/scripts/hudson/runTest
@@ -65,6 +65,11 @@ fi
 CONFIGURE_FLAGS="--with-boost=${ROSE_TEST_BOOST_PATH} --with-boost-libdir=${ROSE_TEST_BOOST_PATH}/lib --with-java=${ROSE_TEST_JAVA_PATH} --with-ROSE_LONG_MAKE_CHECK_RULE=yes"
 
 if test "x$ROSE_TEST_BUILD_STYLE" = "xfull" ; then
+
+ # DQ (1/14/2010): I am debugging the Hudson tests of failures on tux269.
+   echo "This test is forced to exit with an error as part of debugging Hudson tests."
+   exit 1
+
 	CONFIGURE_FLAGS="${CONFIGURE_FLAGS} --with-qt=${ROSE_TEST_QT_PATH} --with-roseQt --with-sqlite3=${ROSE_TEST_SQLITE_PATH} --with-rted=${ROSE_TEST_RTED_PATH}"
 	if test "x$ROSE_TEST_GCC_VERSION" = "x4.1.2" ; then
 		CONFIGURE_FLAGS="${CONFIGURE_FLAGS} --with-pch"
