Still working on getting Hudson into shape.

diff --git a/scripts/hudson/runTest b/scripts/hudson/runTest
--- a/scripts/hudson/runTest
+++ b/scripts/hudson/runTest
@@ -196,7 +196,7 @@ if test "x$ROSE_SPEW_ANALYSIS" = "xyes" ; then
    grep -n "Making all in " filtered_make_output.txt | ../scripts/checkMakeSpew.pl | tee makeSpewLineCount.txt
    echo "Done with compile time spew"
 else
-   make -j16
+#  make -j16
 
    if [ $? -ne 0 ]  ; then
         echo "fatal error during 'make'  , aborting..."
@@ -208,10 +208,20 @@ echo "Done with compile step"
 end_time_make_seconds="$(date +%s)"
 elapsed_make_time_seconds="$(expr $end_time_make_seconds - $start_time_make_seconds)"
 elapsed_make_time_minutes="$(expr $elapsed_make_time_seconds / 60)"
+# elapsed_make_time_modulo_seconds="$(expr $elapsed_make_time_seconds % 60)"
+if test $elapsed_make_time_seconds > 60; then
+   elapsed_make_time_minutes="$(expr ($elapsed_make_time_seconds) / 60)"
+else
+   elapsed_make_time_minutes="$elapsed_make_time_seconds"
+fi
 echo "***********************************************************************************************************"
-echo "Elapsed time for make test: $elapsed_make_time_minutes min $elapsed_make_time_seconds sec"
+echo "Elapsed time for make test: $elapsed_make_time_minutes min $elapsed_make_time_modulo_seconds sec"
 echo "***********************************************************************************************************"
 
+
+ # DQ (1/14/2010): I am debugging the Hudson tests of failures on tux269.
+   echo "Exiting as a test to simplify elapsed time tests."
+   exit 1
 
 # Provide a disk usage report to support debugging when Hudson has a problem.
 # echo "Disk usage report #4 (to support debugging when Hudson has a problem):"
@@ -230,7 +240,7 @@ if test \! \( "x$ROSE_TEST_GCC_VERSION" = "x4.3.2" -o "x$ROSE_TEST_GCC_VERSION" 
    echo "Starting make check step"
  # Andreas suggests that the use of "tee" is not passing error through to Hudson.
  # make -j8 check 2>&1 | tee make_check_output.txt;
-	make -j16 check
+#	make -j16 check
 
  # Or perhaps: ( false || echo "testing" ) | tee make_check_output.txt
  # ( make -j8 check || echo "error detected in make check rule"; exit 1 ) 2>&1 | tee make_check_output.txt
@@ -241,7 +251,12 @@ if test \! \( "x$ROSE_TEST_GCC_VERSION" = "x4.3.2" -o "x$ROSE_TEST_GCC_VERSION" 
 
    end_time_make_check_seconds="$(date +%s)"
    elapsed_make_check_time_seconds="$(expr $end_time_make_check_seconds - $start_time_make_check_seconds)"
-   elapsed_make_check_time_minutes="$(expr $elapsed_make_check_time_seconds / 60)"
+ # elapsed_make_check_time_minutes="$(expr $elapsed_make_check_time_seconds / 60)"
+   if test $elapsed_make_check_time_seconds > 60; then
+      elapsed_make_check_time_minutes="$(expr ($elapsed_make_check_time_seconds) / 60)"
+   else
+      elapsed_make_check_time_minutes="$elapsed_make_check_time_seconds"
+   fi
    echo "***********************************************************************************************************"
    echo "Elapsed time for make check test: $elapsed_make_check_time_minutes min $elapsed_make_check_time_seconds sec"
    echo "***********************************************************************************************************"
@@ -266,7 +281,11 @@ if test \! \( "x$ROSE_TEST_GCC_VERSION" = "x4.3.2" -o "x$ROSE_TEST_GCC_VERSION" 
 
    end_time_make_distcheck_seconds="$(date +%s)"
    elapsed_make_distcheck_time_seconds="$(expr $end_time_make_distcheck_seconds - $start_time_make_distcheck_seconds)"
-   elapsed_make_distcheck_time_minutes="$(expr $elapsed_make_distcheck_time_seconds / 60)"
+   if test $elapsed_make_distcheck_time_seconds > 60; then
+      elapsed_make_distcheck_time_minutes="$(expr ($elapsed_make_distcheck_time_seconds) / 60)"
+   else
+      elapsed_make_distcheck_time_minutes="$elapsed_make_distcheck_time_seconds"
+   fi
    echo "***********************************************************************************************************************"
    echo "Elapsed time for make distcheck test: $elapsed_make_distcheck_time_minutes min $elapsed_make_distcheck_time_seconds sec"
    echo "***********************************************************************************************************************"
@@ -278,7 +297,7 @@ echo "Disk usage report #5 (to support debugging when Hudson has a problem):"
 
 # DQ (12/16/2009): This appears to work everywhere byt on the 4.3.2 systems, verify this.
 # Finally run the "make docs" test (on just the 4.2.4 version of gcc).
-if test \! \( "x$ROSE_TEST_GCC_VERSION" = "x4.3.2" \) ; then
+if test \! \( "x$ROSE_TEST_GCC_VERSION" = "x4.3.2" \); then
    echo "Starting make docs step (exit normally even if it fails so that we can debug the docs rule)"
  # Exit normally even if it fails so that we can debug the docs rule.
  # make -j8 docs || exit 0
