Still working on getting Hudson into shape.

diff --git a/scripts/hudson/runTest b/scripts/hudson/runTest
--- a/scripts/hudson/runTest
+++ b/scripts/hudson/runTest
@@ -24,12 +24,13 @@ echo "*******************************************************************"
 # Output the name of the machine where the build is being run (helpful for debugging).
 machine_name=`uname -n`
 start_time=`date`
+start_time_seconds="$(date +%s)"
 echo ""
-echo "****************************************************"
+echo "*****************************************************************************"
 echo "Executing runTest for ROSE Project on: $machine_name start_time = $start_time"
-echo "Build Disk Usage Report:"
+# echo "Build Disk Usage Report:"
 # df . || pwd
-echo "****************************************************"
+echo "*****************************************************************************"
 
 # Provide a disk usage report to support debugging when Hudson has a problem.
 echo "Disk usage report #1 (to support debugging when Hudson has a problem):"
@@ -103,8 +104,8 @@ CONFIGURE_FLAGS="--with-boost=${ROSE_TEST_BOOST_PATH} --with-boost-libdir=${ROSE
 if test "x$ROSE_TEST_BUILD_STYLE" = "xfull" ; then
 
  # DQ (1/14/2010): I am debugging the Hudson tests of failures on tux269.
-   echo "This test is forced to exit with an error as part of debugging a subset of the Hudson tests."
-   exit 1
+ # echo "This test is forced to exit with an error as part of debugging a subset of the Hudson tests."
+ # exit 1
 
 	CONFIGURE_FLAGS="${CONFIGURE_FLAGS} --with-qt=${ROSE_TEST_QT_PATH} --with-roseQt --with-sqlite3=${ROSE_TEST_SQLITE_PATH} --with-rted=${ROSE_TEST_RTED_PATH}"
 	if test "x$ROSE_TEST_GCC_VERSION" = "x4.1.2" ; then
@@ -172,6 +173,9 @@ echo "Disk usage report #3 (to support debugging when Hudson has a problem):"
 # DQ has confirmed that Andreas's point is true for bash but false for tcsh 
 # (where it was originally tested).
 echo "Starting compile step"
+
+start_time_make_seconds="$(date +%s)"
+
 # if test false; then
 ROSE_SPEW_ANALYSIS=no
 if test "x$ROSE_SPEW_ANALYSIS" = "xyes" ; then
@@ -193,6 +197,7 @@ if test "x$ROSE_SPEW_ANALYSIS" = "xyes" ; then
    echo "Done with compile time spew"
 else
    make -j16
+
    if [ $? -ne 0 ]  ; then
         echo "fatal error during 'make'  , aborting..."
         exit 3
@@ -200,15 +205,26 @@ else
 fi 
 echo "Done with compile step"
 
+end_time_make_seconds="$(date +%s)"
+elapsed_make_time_seconds="$(expr $end_time_make_seconds - $start_time_make_seconds)"
+elapsed_make_time_minutes="$(expr $elapsed_make_time_seconds / 60)"
+echo "***********************************************************************************************************"
+echo "Elapsed time for make test: $elapsed_make_time_minutes min $elapsed_make_time_seconds sec"
+echo "***********************************************************************************************************"
+
+
 # Provide a disk usage report to support debugging when Hudson has a problem.
-echo "Disk usage report #4 (to support debugging when Hudson has a problem):"
-#df /export
+# echo "Disk usage report #4 (to support debugging when Hudson has a problem):"
+# df /export
 
 # GCC 4.3 and 4.4 do not currently pass make check
 # Known unresolved issues:
 #  - RTED test failures due to obsolete STL headers used in test suite
 #  - Unparser generates (C++ and Fortran) code that is incompatible with these compilers
 if test \! \( "x$ROSE_TEST_GCC_VERSION" = "x4.3.2" -o "x$ROSE_TEST_GCC_VERSION" = "x4.4.1" \) ; then
+
+   start_time_make_check_seconds="$(date +%s)"
+
  # DQ (12/9/2009): Save output from "make check" rule and measure the test spew.
  # make -j8 check
    echo "Starting make check step"
@@ -223,11 +239,20 @@ if test \! \( "x$ROSE_TEST_GCC_VERSION" = "x4.3.2" -o "x$ROSE_TEST_GCC_VERSION" 
         exit 3
    fi
 
+   end_time_make_check_seconds="$(date +%s)"
+   elapsed_make_check_time_seconds="$(expr $end_time_make_check_seconds - $start_time_make_check_seconds)"
+   elapsed_make_check_time_minutes="$(expr $elapsed_make_check_time_seconds / 60)"
+   echo "***********************************************************************************************************"
+   echo "Elapsed time for make check test: $elapsed_make_check_time_minutes min $elapsed_make_check_time_seconds sec"
+   echo "***********************************************************************************************************"
+
    echo "Done with make check step"
  # grep -n "Making check in " make_check_output.txt | ../scripts/checkMakeSpew.pl | tee makeCheckSpewLineCount.txt
 
  # The distcheck rule builds a distribution and reruns all the tests; including the rules: install, installcheck
    echo "Starting make distcheck step"
+
+   start_time_make_distcheck_seconds="$(date +%s)"
 
 # FIXME
 #  make -j8 distcheck
@@ -238,6 +263,13 @@ if test \! \( "x$ROSE_TEST_GCC_VERSION" = "x4.3.2" -o "x$ROSE_TEST_GCC_VERSION" 
    fi
 
    echo "Done with make distcheck step"
+
+   end_time_make_distcheck_seconds="$(date +%s)"
+   elapsed_make_distcheck_time_seconds="$(expr $end_time_make_distcheck_seconds - $start_time_make_distcheck_seconds)"
+   elapsed_make_distcheck_time_minutes="$(expr $elapsed_make_distcheck_time_seconds / 60)"
+   echo "***********************************************************************************************************************"
+   echo "Elapsed time for make distcheck test: $elapsed_make_distcheck_time_minutes min $elapsed_make_distcheck_time_seconds sec"
+   echo "***********************************************************************************************************************"
 fi
 
 # Provide a disk usage report to support debugging when Hudson has a problem.
@@ -255,21 +287,35 @@ if test \! \( "x$ROSE_TEST_GCC_VERSION" = "x4.3.2" \) ; then
  # Running with parallelism here does not tend to be very helpful since 
  # doxygen is what has to run and it does not run in parallel.
 
-# FIXME
-#  make -j8 docs
+   start_time_make_docs_seconds="$(date +%s)"
+
+   make -j8 docs
    if [ $? -ne 0 ]  ; then
         echo "fatal error during 'make docs'  , aborting..."
         exit 3
    fi
    echo "Done with make docs step"
+
+   end_time_make_docs_seconds="$(date +%s)"
+   elapsed_make_docs_time_seconds="$(expr $end_time_make_docs_seconds - $start_time_make_docs_seconds)"
+   elapsed_make_docs_time_minutes="$(expr $elapsed_make_docs_time_seconds / 60)"
+   echo "********************************************************************************************************"
+   echo "Elapsed time for make docs test: $elapsed_make_docs_time_minutes min $elapsed_make_docs_time_seconds sec"
+   echo "********************************************************************************************************"
 fi
 
 # Provide a disk usage report to support debugging when Hudson has a problem.
-echo "Disk usage report #6 (to support debugging when Hudson has a problem):"
-#df /export
+# echo "Disk usage report #6 (to support debugging when Hudson has a problem):"
+# df /export
 
-end_time=`date`
-echo ""
-echo "**************************************************************************************************"
-echo "Executing runTest for ROSE Project on: $machine_name start_time = $start_time end_time = $end_time"
-echo "**************************************************************************************************"
+end_time_seconds="$(date +%s)"
+elapsed_hudson_time_seconds="$(expr $end_time_seconds - $start_time_seconds)"
+elapsed_hudson_time_minutes="$(expr $elapsed_seconds / 60)"
+echo "***********************************************************************************************"
+echo "Elapsed time for Hudson test: $elapsed_hudson_time_minutes min $elapsed_hudson_time_seconds sec"
+echo "***********************************************************************************************"
+
+#end_time=`date`
+#echo "**************************************************************************************************"
+#echo "Executing runTest for ROSE Project on: $machine_name start_time = $start_time end_time = $end_time"
+#echo "**************************************************************************************************"
