Modified hudson test scripts to count output spew while properly handling errors.

diff --git a/scripts/hudson/runTestAll b/scripts/hudson/runTestAll
--- a/scripts/hudson/runTestAll
+++ b/scripts/hudson/runTestAll
@@ -194,14 +194,20 @@ echo "Starting compile step"
 start_time_make_seconds="$(date +%s)"
 
 # if test false; then
-ROSE_SPEW_ANALYSIS=no
+ROSE_SPEW_ANALYSIS=yes
 if test "x$ROSE_SPEW_ANALYSIS" = "xyes" ; then
 
  # DQ (1/14/2010): I am debugging the Hudson tests of failures on tux269.
-   echo "It should be impossible to reach this branch (exiting in false branch)."
-   exit 1
+ #  echo "It should be impossible to reach this branch (exiting in false branch)."
 
-   make -j8 2>&1 | tee make_output.txt
+   make -j8 2>&1 | tee make_output.txt 
+
+ # the pipestatus variable is an array that holds the exit status of your last foreground pipeline commands.
+ # we check to see if make failes through this command
+   if [ ${PIPESTATUS[0]} -ne 0 ]  ; then
+        echo "fatal error during 'make'  , aborting..."
+        exit 3
+   fi
 
 # Filter out the legitimate lines specific to compilation and linking (filter compile, links, and Qt specific tools).
    echo "Building the filtered_make_output.txt file"
