Added version checking for libtool to build script (and modified NMI options).
git-svn-id: file:///usr/casc/overture/ROSE/svn/ROSE/trunk/ROSE@7666 a27c51de-2d2b-4d1b-a6e8-f7f87814f453

diff --git a/build b/build
--- a/build
+++ b/build
@@ -7,8 +7,8 @@ while [ "$#" -gt 0 ]; do
     arg="$1"; shift
     case "$arg" in
         --verbose)
-	    do_quiet=no
-	    ;;
+            do_quiet=no
+            ;;
         --timing)
             do_timing=yes
             ;;
@@ -35,16 +35,121 @@ rm -rf autom4te.cache
 # my own libtool installation)
 # DQ (2/10/2009): Must use "/Users/dquinlan/local/libtool-install/bin/libtoolize --force --copy --ltdl --automake"
 # the first time.
-if which libtoolize > /dev/null; then
-  libtoolize --force --copy --ltdl --automake
-elif which glibtoolize > /dev/null; then
-  glibtoolize --force --copy --ltdl --automake
+
+# This only detects the file in the current directory (not in directories given by the PATH variable).
+# if test -x libtoolize; then
+#   echo "libtoolize exists!"
+# else
+#   echo "libtoolize does not exist!"
+# fi
+
+# Original code:
+# if which libtoolize > /dev/null; then
+#    libtoolize --force --copy --ltdl --automake
+# elif which glibtoolize > /dev/null; then
+#    glibtoolize --force --copy --ltdl --automake
+# fi
+
+libtoolize_name=""
+test_libtoolize_version=""
+run_libtoolize=""
+
+echo "******************************************"
+echo "Testing version of libtool (libtoolize)..."
+echo "******************************************"
+
+# DQ (9/29/2009): Check if libtoolize is available in the user's path, else check for glibtoolize (less common, I think).
+if test ! `which libtoolize > /dev/null`; then
+   echo "Found libtoolize program, running it to generate libtool locally in ROSE."
+   libtoolize_name=libtoolize
+   test_libtoolize_version=yes
+else
+   if test ! `which glibtoolize > /dev/null`; then
+      echo "Found glibtoolize program, running it to generate libtool locally in ROSE."
+      libtoolize_name=glibtoolize
+      test_libtoolize_version=yes
+   else
+    # If the user is running build then libtool should be available.
+      echo "Can't find libtool support (libtoolize)...(using the version that comes with ROSE)"
+      test_libtoolize_version=no
+    # exit 1;
+   fi
 fi
 
+# Specify what version we require (at least)
+LIBTOOL_VERSION_MAJOR_PREREQ=1
+LIBTOOL_VERSION_MINOR_PREREQ=5
+LIBTOOL_VERSION_PATCH_PREREQ=6
+
+LIBTOOL_VERSION_MAJOR=`echo|$libtoolize_name --version | head -1 | sed s/"libtoolize (GNU libtool) "//g | cut -f1 -d \) | cut -d\. -f1`
+LIBTOOL_VERSION_MINOR=`echo|$libtoolize_name --version | head -1 | sed s/"libtoolize (GNU libtool) "//g | cut -f1 -d \) | cut -d\. -f2`
+LIBTOOL_VERSION_PATCH=`echo|$libtoolize_name --version | head -1 | sed s/"libtoolize (GNU libtool) "//g | cut -f1 -d \) | cut -d\. -f3`
+
+echo "Libtool version is $LIBTOOL_VERSION_MAJOR.$LIBTOOL_VERSION_MINOR.$LIBTOOL_VERSION_PATCH (ROSE requires at least $LIBTOOL_VERSION_MAJOR_PREREQ.$LIBTOOL_VERSION_MINOR_PREREQ.$LIBTOOL_VERSION_PATCH_PREREQ)"
+
+if test $test_libtoolize_version = "yes"; then
+
+ # Run libtoolize unless the version in ROSE is the latest version.
+   run_libtoolize=yes
+
+ # Report the current version of libtool to be used...
+ # echo "Libtool version is $LIBTOOL_VERSION_MAJOR.$LIBTOOL_VERSION_MINOR.$LIBTOOL_VERSION_PATCH (ROSE requires at least $LIBTOOL_VERSION_MAJOR_PREREQ.$LIBTOOL_VERSION_MINOR_PREREQ.$LIBTOOL_VERSION_PATCH_PREREQ)"
+
+   if test $LIBTOOL_VERSION_MAJOR -eq $LIBTOOL_VERSION_MAJOR_PREREQ; then
+    # echo "Libtool major version number is correct: LIBTOOL_VERSION_MAJOR = $LIBTOOL_VERSION_MAJOR (requires $LIBTOOL_VERSION_MAJOR_PREREQ)"
+      if test $LIBTOOL_VERSION_MINOR -eq $LIBTOOL_VERSION_MINOR_PREREQ; then
+       # echo "Libtool minor version number is correct: LIBTOOL_VERSION_MINOR = $LIBTOOL_VERSION_MINOR (requires $LIBTOOL_VERSION_MINOR_PREREQ)"
+         if test $LIBTOOL_VERSION_PATCH -eq $LIBTOOL_VERSION_PATCH_PREREQ; then
+          # echo "Libtool patch version number is correct: LIBTOOL_VERSION_PATCH = $LIBTOOL_VERSION_PATCH (requires $LIBTOOL_VERSION_PATCH_PREREQ)"
+            :
+         else
+          # Allow patch version 7 and greater to pass (I don't think there is anything between 1.9.6 and 1.10, but just in case)
+            if test $LIBTOOL_VERSION_PATCH -lt $LIBTOOL_VERSION_PATCH_PREREQ; then
+               echo "Warning: Libtool patch version number too old:    LIBTOOL_VERSION_PATCH = $LIBTOOL_VERSION_PATCH (requires $LIBTOOL_VERSION_PATCH_PREREQ)"
+               run_libtoolize=no
+             # exit 1;
+            fi
+         fi
+      else
+       # Allow minor version 10 and greater to pass (minor version values of 10 are avalable)
+         if test $LIBTOOL_VERSION_MINOR -lt $LIBTOOL_VERSION_MINOR_PREREQ; then
+            echo "Warning: Libtool minor version number too old:    LIBTOOL_VERSION_MINOR = $LIBTOOL_VERSION_MINOR (requires $LIBTOOL_VERSION_MINOR_PREREQ)"
+            run_libtoolize=no
+          # exit 1;
+         fi
+      fi
+   else
+    # Allow major version numbers greater than 1 (when they are available) to pass
+      if test $LIBTOOL_VERSION_MAJOR -lt $LIBTOOL_VERSION_MAJOR_PREREQ; then
+         echo "Warning: Libtool major version number too old:    LIBTOOL_VERSION_MAJOR = $LIBTOOL_VERSION_MAJOR (requires $LIBTOOL_VERSION_MAJOR_PREREQ)"
+         run_libtoolize=no
+       # exit 1;
+      fi
+   fi
+
+ # Run the libtoolize to copy the local version into place for use by ROSE.
+ # But only if it is newer then (or the same as) version 1.5.6.
+   if test $run_libtoolize = "yes"; then
+      echo "Running libtoolize: $libtoolize_name --force --copy --ltdl --automake"
+      $libtoolize_name --force --copy --ltdl --automake
+   else
+    # Note that the internal SVN repository does not have a version of libtool included in ROSE,
+    # but the external SVN repository does include a version of libtool distributed with ROSE.
+    # This is done to save users from finding the correct version of libtool if it is locally 
+    # unavailable. This is a relatively common practice within projects using libtool.
+      echo "Skipping libtoolize: \"$libtoolize_name --force --copy --ltdl --automake\" (using version distributed with in ROSE, if present)"
+   fi
+fi
+
+# echo "Exiting ./build script as a test!"
+# exit 1
+
 # DQ (11/23/2008): Added message to make users less afraid of warnings...
+echo ""
 echo "*******************************************************************************************"
 echo "Note that due to ROSE compatibility with libtool 1.5 and 2.0, some warnings will be output."
 echo "These warnings come from configure.in and aclocal.m4, and can be safely ignored."
+echo "These messages from from the use of aclocal, acheader, autoconf, and automake."
 echo ""
 echo "Rose Project Management."
 echo "*******************************************************************************************"
@@ -70,7 +175,7 @@ AUTOMAKE_VERSION_MAJOR_PREREQ=1
 AUTOMAKE_VERSION_MINOR_PREREQ=9
 AUTOMAKE_VERSION_PATCH_PREREQ=6
 
-echo "testing version of automake.."
+echo "testing version of automake..."
 AUTOMAKE_VERSION_MAJOR=`echo|automake --version | head -1 | sed s/"automake (GNU automake) "//g | cut -f1 -d \) | cut -d\. -f1`
 AUTOMAKE_VERSION_MINOR=`echo|automake --version | head -1 | sed s/"automake (GNU automake) "//g | cut -f1 -d \) | cut -d\. -f2`
 AUTOMAKE_VERSION_PATCH=`echo|automake --version | head -1 | sed s/"automake (GNU automake) "//g | cut -f1 -d \) | cut -d\. -f3`
