Added more support for dynamic binary instrumentation using Intel Pin (--with-IntelPin).
Detailed changes in this commit:
   1) Added more examples of the connection between Intel Pin and ROSE.
   2) Added example of commandline handling required for ROSE.
   3) resolved both static and dynamic linking issues associated with using 
      Pin tools that contain ROSE static analysis.
   4) Note that dwarf support in ROSE does not work with Intel Pin.  Pin 
      tools using ROSE configured to use Dwarf fail in call to the dwarf_init()
      function, first libdwarf function called by ROSE).
   5) Configuration of ROSE fixed to exit with error if both --with-dwarf and 
      --with-IntelPin options are used.
   6) Added example scripts/zgrviewerExampleScript to show how to use zgrviewer
      with Java to allow the VM to use more meory as required for large DOT graphs.





git-svn-id: file:///usr/casc/overture/ROSE/svn/ROSE/trunk/ROSE@4828 a27c51de-2d2b-4d1b-a6e8-f7f87814f453

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -345,6 +345,16 @@ ROSE_SUPPORT_DWARF
 # Setup Automake conditional in --- (not yet distributed)
 AM_CONDITIONAL(ROSE_USE_DWARF,test ! "$with_dwarf" = no)
 
+# DQ (3/10/2009): The Dwarf support in Intel Pin conflicts with the Dwarf support in ROSE.
+# Maybe there is a way to fix this later, for now we want to disallow it.
+# echo "with_dwarf    = $with_dwarf"
+# echo "with_IntelPin = $with_IntelPin"
+if test "$with_dwarf" != no && test "$with_IntelPin" != no; then
+ # echo "Support for both DWARF and Intel Pin fails, these configure options are incompatable."
+   AC_MSG_ERROR([Support for both DWARF and Intel Pin fails, these configure options are incompatable!])
+#   exit 1
+fi
+
 ROSE_SUPPORT_PHP
 
 AM_CONDITIONAL(ROSE_USE_PHP,test ! "$with_php" = no)
