Fixed computation of major and minor version numbers for gfortran 4.0 compiler (error now caught in configure (later than before)).
git-svn-id: file:///usr/casc/overture/ROSE/svn/ROSE/trunk/ROSE@7309 a27c51de-2d2b-4d1b-a6e8-f7f87814f453

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -251,6 +251,15 @@ AX_BOOST_WAVE
 AX_LIB_SQLITE3
 AX_LIB_MYSQL
 
+# DQ (9/15/2009): I have moved this to before the backend compiler selection so that
+# we can make the backend selection a bit more compiler dependent. Actually we likely
+# don't need this!
+# DQ (9/17/2006): These should be the same for both C and C++ (else we will need separate macros)
+# Setup the -D<xxx> defines required to allow EDG to take the same path through the compiler 
+# specific and system specific header files as for the backend compiler.  These depend
+# upon the selection of the back-end compiler.
+# GET_COMPILER_SPECIFIC_DEFINES
+
 # Test this macro here at the start to avoid long processing times (before it fails)
 CHOOSE_BACKEND_COMPILER
 
@@ -550,6 +559,16 @@ if test "x$USE_JAVA" = x1; then
     ofp_enabled=yes
     AC_MSG_RESULT([yes])
     AC_DEFINE([USE_GFORTRAN_IN_ROSE], [1], [Mark that GFORTRAN is available])
+
+  # Test that we have correctly evaluated the major and minor versions numbers...
+    if test x$BACKEND_FORTRAN_COMPILER_MAJOR_VERSION_NUMBER == x; then
+      echo "Error: Could not compute the MAJOR version number of $BACKEND_FORTRAN_COMPILER"
+      exit 1
+    fi
+    if test x$BACKEND_FORTRAN_COMPILER_MINOR_VERSION_NUMBER == x; then
+      echo "Error: Could not compute the MINOR version number of $BACKEND_FORTRAN_COMPILER"
+      exit 1
+    fi
   else
     AC_MSG_RESULT([no ... gfortran cannot be found (try --with-gfortran)])
   fi
