Simplified and sped up header file creation process
git-svn-id: file:///usr/casc/overture/ROSE/svn/ROSE/trunk/ROSE@1136 a27c51de-2d2b-4d1b-a6e8-f7f87814f453

diff --git a/config/create_system_headers b/config/create_system_headers
--- a/config/create_system_headers
+++ b/config/create_system_headers
@@ -12,149 +12,16 @@
 # for processing all headers in a directory and its sub directories
 
 ######################################################################################
-# the process_headers_in_dir() function takes as arguments a compiler name, 
-# source and target directory. Both paths should be given as full paths to
-# avoid the overhead of again resolving out what the full path is. It will 
-# be assumed that all error checking has been done prior to this to ensure 
-# that the src and target directories exist.
-# Usage: process_headers_in_dir compiler_name src_dir target_dir
-
-process_headers_in_dir()
-{
- # echo "In process_headers_in_dir: parameter 1 = $1  parameter 2 = $2 parameter 3 = $3 parameter 4 = $4"
-   cd "$2"
-   for fName in *
-   do
-      [ -f "$fName" ] || continue 
-      case "$fName" in
-        *.c | *.cc | *.C | *.cxx ) cp "$fName" "$3";; # copy source files without processing
-        *) process_file "$1" "$fName" "$3" "$4";;
-      esac
-   done
-}
-
-
-######################################################################################
-# process using compiler
-# Usage: process_file compilerName sourceFile targetDir
-# check to see if files contain include_next directives
-# if so, replace by #include "/usr/include/..." else
-# simply copy to target dir
-process_file()
-{
-   compilerName=`basename "$1"`
-   pwdVar=`pwd`
-
- # DQ (5/29/2003) Adding support for using rose_varargs.h
- # echo "In process_file(): compilerName = $compilerName"
- # echo "In process_file(): parameter 1 = $1  parameter 2 = $2 parameter 3 = $3 parameter 4 = $4"
- # echo "In process_file(): new file location = $3/$2"
- # echo "In process_file(): pwd = $pwdVar parameter 1 = $1  parameter 2 = $2 parameter 3 = $3 parameter 4 = $4"
-
-   case "$compilerName" in     # figure out which compiler we are using
-   CC) cp "$2" "$3" 2>/dev/null;;       # copy directly
-   g++|gcc )
-      # DQ (8/28/2004): The gnu-3.x-headerfile-fixup.pl is used to process the backend compiler's
-      # header files as required.  For some systems no processing is required.  However, for GNU
-      # there is some processing (non-standard features) which the g++ compiler implements just to
-      # be able to process its own header files.  Since we can't implement these language features
-      # in ROSE, we process the header files to remove or fixup the the non-standard parts of the
-      # header files.  In general the header files match the header files associated with the
-      # backend compiler used with ROSE.
-        if  [ ! -f "$4/config/gnu-3.x-headerfile-fixup.pl" ]
-        then
-             echo "ERROR: $4/config/gnu-3.x-headerfile-fixup.pl does not exist"
-             exit 2
-        fi
-      # echo "Calling $4/config/gnu-3.x-headerfile-fixup.pl $2 > $3/$2"
-      # $4/config/gnu-3.x-headerfile-fixup.pl $2 > $3/$2 2>/dev/null;;
-        $4/config/gnu-3.x-headerfile-fixup.pl $2 > $3/$2;;
-   KCC) sed 's/# *__include_next *["<]\(.*\)[">]/#include "\/usr\/include\/\1"/' $2 > $3/$2 2>/dev/null;;
-   icpc|icc ) 
-     #AS (6/14/06) icc/icpc with GNU compatibility will require the GNU header fixups as stated above in the
-     # g++|gcc section
-     if  [ ! -f "$4/config/gnu-3.x-headerfile-fixup.pl" ]
-        then
-             echo "ERROR: $4/config/gnu-3.x-headerfile-fixup.pl does not exist"
-             exit 2
-        fi
-      # echo "Calling $4/config/gnu-3.x-headerfile-fixup.pl $2 > $3/$2"
-        $4/config/gnu-3.x-headerfile-fixup.pl $2 > $3/$2 2>/dev/null;;
-   *) echo "ERROR: Compiler $1 not recognized as supported backend for ROSE translators"
-      exit 6;;
-   esac
-
- # *******************************************************************************
- # Compiler independent modifications to the backend compiler's header file system
- # *******************************************************************************
-
- # DQ (6/23/2004): Work with Olav Beckman determined that this "==" must be "=" under CygWin!
- # strip out all ^M characters (a problem for the sstream header file on Linux machines)
-# JJW 6-11-2008: This is unlikely to be needed anymore
-#    if [ $2 = "sstream" ]
-#    then
-#       echo "Processing (removing) ^M characters from sstream file at $3/$2"
-#       sed -e s/\//g $3/$2 > $3/tempFile 2>/dev/null;
-#       cp $3/tempFile $3/$2;
-#    fi
-
- # DQ (10/31/2005): The Complex header file needs to be modified to work with ROSE.
- # The following solution does work.  Replacing
- #   complex(_ComplexT __z) : _M_value(__z) { }
- # with
- #   explicit complex(_ComplexT __z) : _M_value(__z) { }
- # in the complex header file.  See notes in: 
- # rose_edg_required_macros_and_functions.h
-   if [ $2 = "complex" ]
-   then
-      echo "Processing complex header file (commenting out private constructor) at $3/$2"
-      sed -e 's/complex(_ComplexT __z)/\/\/ ***commented out for ROSE*** complex(_ComplexT __z)/g' $3/$2 > $3/tempFile 2>/dev/null;
-      cp $3/tempFile $3/$2;
-   fi
-
- # JJW (10/29/2007): In GCC 4.2, the system header files use the visibility
- # attribute which EDG 3.3 does not support.  A #define can be changed to turn
- # that feature off, though.  Also, the built-in synchronization functions in
- # new versions of GCC are not yet supported in ROSE, so turn them off too.
-   if [ $2 = "c++config.h" ]
-   then
-      echo "Processing c++config header file (removing use of visibility attribute) at $3/$2"
-      # Avoid sed -i which doesn't have the same behavior on BSD
-      cat $3/$2 | \
-        sed 's/# *define _GLIBCXX_HAVE_ATTRIBUTE_VISIBILITY 1/#define _GLIBCXX_HAVE_ATTRIBUTE_VISIBILITY 0/' | \
-        sed 's/# *define _GLIBCXX_ATOMIC_BUILTINS/#undef _GLIBCXX_ATOMIC_BUILTINS/' > "$3/tempfile"
-      cp "$3/tempfile" "$3/$2"
-   fi
-
-}
-
-######################################################################################
 
 process_headers()
 {
 
 # make sure the source directory structure exists
-  if  [ ! -d "$2" ]
+  if  [ ! -d "$2" -o ! -r "$2" -o ! -x "$2" ]
   then
-    echo "ERROR: Directory $2 does not exist"
+    echo "ERROR: Directory $2 is invalid"
     echo "*************  FAILING ***** FAILING *****************"
     exit 2
-  fi
-
-# make sure we can read the source directory structure
-  if [ ! -r "$2" ]
-  then
-    echo "ERROR: Directory $2 is not readable"
-    echo "*************  FAILING ***** FAILING *****************"
-    exit 3
-  fi
-
-# make sure we can search the source directory structure
-  if [ ! -x "$2" ]
-  then
-    echo "ERROR: Directory $2 is not searchable"
-    echo "*************  FAILING ***** FAILING *****************"
-    exit 4
   fi
 
 # get full path for the current working directory, the src and target dirs
@@ -185,23 +52,34 @@ process_headers()
   then
     echo "ERROR: Target directory cannot be created (Parent directory $target_parent_dir not writable)"
     exit 5
-  else
-    if [ ! -d $target_dir ]  # if the target directory does not exist create it
-    then
-      mkdir $target_dir
-    fi
-    # get the list of src directories to process
-    listOfSrcDirs=`find "$src_dir" -follow -type d -print 2>/dev/null`
-    for srcDirName in $listOfSrcDirs
-    do
-     # echo "processing files in directory $srcDirName to put into $targetDirName"
-     # this is not the most efficient thing to do ...
-       targetDirName=`echo "$srcDirName" | sed "s|$src_dir|$target_dir|g"`
-     # create if it does not exist
-       [ -d $targetDirName ] || mkdir $targetDirName
-       process_headers_in_dir "$1" "$srcDirName" "$targetDirName" "$roseHome"
-    done
   fi
+  mkdir -p $target_dir
+  cp -Rp $src_dir/* $target_dir/
+  echo "Done copying"
+  # Find the special-case files to process
+  find "$src_dir/." \( -name complex -o -name c++config.h \) -a -type f -a -print 2>/dev/null | \
+  while read srcName; do
+   # echo "processing files in directory $srcDirName to put into $targetDirName"
+   # this is not the most efficient thing to do ...
+     targetName=`echo "$srcName" | sed "s|$src_dir|$target_dir|g"`
+     case "`basename $srcName`" in
+       "complex" )
+         echo "Processing complex header file (commenting out private constructor) at $targetName"
+         sed -e 's@complex(_ComplexT __z)@// ***commented out for ROSE*** complex(_ComplexT __z)@g' $srcName > $targetName 2>/dev/null
+         ;;
+       "c++config.h" )
+         # JJW (10/29/2007): In GCC 4.2, the system header files use the visibility
+         # attribute which EDG 3.3 does not support.  A #define can be changed to turn
+         # that feature off, though.  Also, the built-in synchronization functions in
+         # new versions of GCC are not yet supported in ROSE, so turn them off too.
+         echo "Processing c++config header file (removing use of visibility attribute) at $targetName"
+         cat $srcName | \
+           sed 's/# *define _GLIBCXX_HAVE_ATTRIBUTE_VISIBILITY 1/#define _GLIBCXX_HAVE_ATTRIBUTE_VISIBILITY 0/' | \
+           sed 's/# *define _GLIBCXX_ATOMIC_BUILTINS/#undef _GLIBCXX_ATOMIC_BUILTINS/' > "$targetName"
+         ;;
+       * ) echo "Should not get here -- modify find pattern" >&2; exit 1 ;;
+     esac
+  done
 
  # DQ (4/11/2005): Copy the header file that is to be read first (within EDG processing) into the compile tree.
  # echo "Copying $roseHome/config/rose_edg_required_macros_and_functions.h to $target_parent_dir"
@@ -215,20 +93,10 @@ process_headers()
 # start of main
 # check for correct number of arguments and 
 # whether a source directory has been specified
-if [ ! $# -ge 3 ]
-then
-#  echo "ERROR: Usage is create_system_headers compiler [src_dir] target_dir"
-   echo "ERROR: Usage is create_system_headers compiler target_dir source_dir"
-   exit 1
-elif [ $# -eq 3 ]        # in this case only compiler name and target_dir and source_dir are specified
-then
-   srcDirsSpecified=1
- # echo "srcDirsSpecified == TRUE"
- # echo "Attempting to automatically determine $1 specific header file directories ..."
+if [ $# -eq 3 ]; then
+  :
 else
-   srcDirsSpecified=0
- # echo "srcDirsSpecified == FALSE"
-   echo "ERROR: Usage is create_system_headers compiler target_dir source_dir"
+   echo "ERROR: Usage is $0 <compiler> <target_dir> <source_dir>"
    exit 1
 fi
 
@@ -281,15 +149,11 @@ is_C_compiler="no"
 
 #AS moved the mkdir of $mainTargetDir here because the ICC and gcc case need it below
 # we will first ensure that targetDirName exists
-if [ ! -d "$mainTargetDir" ]
-then
-   if [ ! -f "$mainTargetDir" ]  # ensure that a file by the same name does not exist
-   then
-      mkdir "$mainTargetDir"     # create main target directory if it does not exist
-      [ -d "$mainTargetDir" ] && echo "created target directory"
-   else
-      echo "ERROR: cannot create target directory $mainTargetDir, file of the same name exists !!"
-   fi
+if mkdir -p "$mainTargetDir"; then
+  : # echo "created target directory"
+else
+  echo "ERROR: cannot create target directory $mainTargetDir"
+  exit 1
 fi
 
 if [ ! -w "$mainTargetDir" ]
@@ -299,64 +163,44 @@ then
 fi
 
 
-if [ $srcDirsSpecified -eq 0 ]    # src directory has been specified
-then
-   nDirs=`expr "$#" - 1`
-   compilerHeadersDir=`echo $* | cut -f 2-$nDirs -d" "`
-else
- # no src dir specified, try to determine automatically based on compiler name
-   case "$compilerName" in
-    # Support for compiling ROSE with KAI KCC compiler (KAI has been bought by Intel and discontinued)
-      KCC) compilerHeadersDir=`"$1" -v 2>&1 | awk '{for(i=1; i<=NF; i++) {if ($i ~ /-I[^ ]*\/include/) { print substr($i, 3); break } } }'`;;
-    # Support for compiling ROSE with GNU g++ compiler
-      g++|gcc|icpc|icc)
-           if [ "$compilerName" = "gcc" -o "$compilerName" = "icc" ]
-           then
-              is_C_compiler="yes"
-			  language="c"
-           else
-			  language="c++"
-           fi
+# no src dir specified, try to determine automatically based on compiler name
+ case "$compilerName" in
+  # Support for compiling ROSE with GNU g++ compiler
+    g++|gcc|icpc|icc)
+         if [ "$compilerName" = "gcc" -o "$compilerName" = "icc" ]
+         then
+            is_C_compiler="yes"
+            language="c"
+         else
+            language="c++"
+         fi
 
-           compilerHeadersDir=`"$1" -v -E -x $language /dev/null 2>&1 | \
-               sed -n '/^#include </,/^End/p' | sed '/^#include </d; /^End/d; /\/usr\/include$/d; /\/Library\/Frameworks$/d; /[(]framework directory[)]$/d'`
+         compilerHeadersDir=`"$1" -v -E -x $language /dev/null 2>&1 | \
+             sed -n '/^#include </,/^End/p' | sed '/^#include </d; /^End/d; /\/usr\/include$/d; /\/Library\/Frameworks$/d; /[(]framework directory[)]$/d'`
 
-         # DQ (1/14/2007): To work with Wave we supress the __STDC_HOSTED__ macro
-           tmpFile="`mktemp -t roseconfigtemp`"
-           "$1" -E -dM -x $language /dev/null \
-                | grep -v "__GNUG__" | grep -v "__GNUC__" | grep -v "__GNUC_MINOR__" | grep -v "__GNUC_PATCHLEVEL__" \
-                | grep -v "__cplusplus" | grep -v "__DATE__" | grep -v "__TIME__" | grep -v "__EDG__" | grep -v "__GXX_WEAK__" \
-                | grep -v "__EDG_VERSION__" | grep -v "_WCHAR_T " | grep -v "__NO_STRING_INLINES" | grep -v "__STDC_HOSTED__" > "$tmpFile"
-           sed "/REPLACE_ME_WITH_MACRO_DEFINITIONS/r$tmpFile" < $roseHome/config/rose_edg_required_macros_and_functions.h.in > $mainTargetDir/rose_edg_required_macros_and_functions.h
-		   rm $tmpFile
+       # DQ (1/14/2007): To work with Wave we supress the __STDC_HOSTED__ macro
+         tmpFile="`mktemp -t roseconfigtemp`"
+         "$1" -E -dM -x $language /dev/null | grep -F -w -f $roseHome/config/macro_names_to_remove > "$tmpFile"
+         sed "/REPLACE_ME_WITH_MACRO_DEFINITIONS/r$tmpFile" < $roseHome/config/rose_edg_required_macros_and_functions.h.in > $mainTargetDir/rose_edg_required_macros_and_functions.h
+         rm $tmpFile
 
-         # echo "PREPROCESSOR_DEFS = $PREPROCESSOR_DEFS"
-           echo "Generating  $mainTargetDir/rose_edg_required_macros_and_functions.h"
-           ;;
-
-    # Support for compiling ROSE with SUN CC compiler (not used since 2003 or so)
-      CC) 
-           tmpFile="/tmp/tmp`uname -n`$$.C"
-           echo "#include <sysent.h>" > "$tmpFile"  
-           hdrFileName=`"$1" -xM1 "$tmpFile" 2>/dev/null | awk '/[^ ]*\/SUNWspro\/[^ ]*\/include\/CC/{print $3; exit }'`
-           rm -f "$tmpFile" 2>/dev/null
-           compilerHeadersDir=`dirname "$hdrFileName"`
-           [ -d "$compilerHeadersDir" ] || echo "ERROR: unable to find C++ header files for CC"
-           ;;
-
-    # Support for compiling ROSE with ROSE (must use translator named: "roseTranslator"
-      roseTranslator) 
-           tmpFile="/tmp/tmp`uname -n`$$.C"
-           echo "int main(int argc, char **argv){return 0;}" > "$tmpFile"
-           compilerHeadersDir=`"$1" -v -E "$tmpFile" 2>&1 | \
-           sed -n '/^#include </,/^End/p' | sed '/^#include </d; /^End/d; /\/usr\/include$/d'`
-           echo "Compile headers dir ${compilerHeadersDir}"
-           ;;
-      *) echo "ERROR: Not able to recognize compiler $1"
-         echo "ERROR: Usage is create_system_headers compiler [src_dir] target_dir"
+       # echo "PREPROCESSOR_DEFS = $PREPROCESSOR_DEFS"
+         echo "Generating  $mainTargetDir/rose_edg_required_macros_and_functions.h"
          ;;
-   esac
-fi
+
+  # Support for compiling ROSE with ROSE (must use translator named: "roseTranslator"
+    roseTranslator) 
+         tmpFile="/tmp/tmp`uname -n`$$.C"
+         echo "int main(int argc, char **argv){return 0;}" > "$tmpFile"
+         compilerHeadersDir=`"$1" -v -E "$tmpFile" 2>&1 | \
+         sed -n '/^#include </,/^End/p' | sed '/^#include </d; /^End/d; /\/usr\/include$/d'`
+         echo "Compile headers dir ${compilerHeadersDir}"
+         ;;
+    *) echo "ERROR: Not able to recognize compiler $1"
+       echo "ERROR: Usage is create_system_headers compiler target_dir src_dir"
+       exit 1
+       ;;
+ esac
 
 # echo "local script variable compilerHeadersDir = $compilerHeadersDir"
 # echo "Building separate header directories"
@@ -405,33 +249,25 @@ echo "system_headers_directory = $system_headers_directory should be used instea
 # support this (gnu does however as an extension).  This is a problem for EDG and we fix it this way.
 
 echo "Copying $roseHome/config/rose_specific_cdefs.h to $system_headers_directory/sys to fix __gconv_info incomplete definition problem ..."
-if [ -d $system_headers_directory/sys ]
-then
-   echo "$system_headers_directory/sys already exists"
-else
-   echo "$system_headers_directory/sys not found, so building it"
-   mkdir -p $system_headers_directory/sys
-fi
+mkdir -p $system_headers_directory/sys
 # cp $roseHome/config/rose_specific_cdefs.h $target_parent_dir/sys/cdefs.h
 cp $roseHome/config/rose_specific_cdefs.h $system_headers_directory/sys/cdefs.h
 
 error_code=$?
-echo "error_code = $error_code"
 if test $error_code != 0; then
-     echo "Error in cp $roseHome/config/rose_specific_cdefs.h $system_headers_directory/sys/cdefs.h: nonzero exit code returned to caller error_code = $error_code"
+     echo "Error in cp $roseHome/config/rose_specific_cdefs.h $system_headers_directory/sys/cdefs.h: nonzero exit code returned to caller error_code = $error_code" >&2
      exit 1
 fi
 
 if [ is_C_compiler = "yes" ]
 then
-    echo "We are handling C compiler specific details, so copy the ROSE specific fix for complex.h to $system_headers_directory"
+    echo "We are handling C compiler specific details, so copy the ROSE specific fix for complex.h to $system_headers_directory" >&2
     cp $roseHome/config/rose_specific_complex.h $system_headers_directory/complex.h
 fi
 
 error_code=$?
-echo "error_code = $error_code"
 if test $error_code != 0; then
-     echo "Error in cp $roseHome/config/rose_specific_complex.h $system_headers_directory/complex.h: nonzero exit code returned to caller error_code = $error_code"
+     echo "Error in cp $roseHome/config/rose_specific_complex.h $system_headers_directory/complex.h: nonzero exit code returned to caller error_code = $error_code" >&2
      exit 1
 fi
 
