runtest returns 0
darcs-hash:20071105143756-a1b90-6117e4c27d97c20f8c73c30b6a683e2d59ece015.gz

diff --git a/projects/SATIrE/examples/constprop/runtests b/projects/SATIrE/examples/constprop/runtests
--- a/projects/SATIrE/examples/constprop/runtests
+++ b/projects/SATIrE/examples/constprop/runtests
@@ -70,8 +70,10 @@ echo "[$GOOD/$TOTAL] succeeded ($PERCENT%)!" # FIXME: integer only
 echo "[$BAD/$TOTAL] failed:"
 if [ -n "$FAILED" ]; then 
     for f in $FAILED; do
-	echo $f
+	echo "  $f"
     done
-    exit 1
+    echo "Press <Ctrl-C> to abort or <Return> to continue"
+    read 
+    #exit 1
 fi
 echo "########################################################################"
