Hooked up importRoseDistributionToSVN with roseFreshTestBinaryDistribution
git-svn-id: file:///usr/casc/overture/ROSE/svn/ROSE/trunk/ROSE@1379 a27c51de-2d2b-4d1b-a6e8-f7f87814f453

diff --git a/scripts/importRoseDistributionToSVN b/scripts/importRoseDistributionToSVN
--- a/scripts/importRoseDistributionToSVN
+++ b/scripts/importRoseDistributionToSVN
@@ -1,47 +1,59 @@
 #!/bin/bash -v
 #
-# This script examines a ROSE distribution package and treats it as a vendor drop
-# to an external Subversion repository.
-# First, it conducts sanity check for the package, especially
+# This script locates a distribution package in a ROSE test directory.
+#  examines the package and imports it as a vendor drop into an external repository.
+# It assumes a layout of test dir as following:
+#   x. sourcetree: a checkout copy of ROSE
+#   x. build: a build dir for ROSE
+# It conducts sanity check for the package, especially
 #   x. Remove .svn directories
 #   x. Make sure no EDG copyrighted files exist
-# Second, it imports the package which passes the check to 
+# It imports the package which passes the check to 
 #  the head of an external repository using svn_load_dirs.1.4.5.pl
 # Use
-#  update the values of ROSE_COPY, WORK_DIR when necessary 
-#  thisScript distro-package.tar.gz
+#  thisScript ROSE_TOP_TEST_DIR
 #
 # by Liao, 7/31/2008
 # Last Modified 7/30/2008
 #------------------------------------------------------
 
+REMOTE_SVN_REPOS=file:////home/liao6/test3/ROSE.MIRROR
+#REMOTE_SVN_REPOS=https://outreach.scidac.gov/svn/rose
+
 if [ $# -lt 1 ]
 then
-  echo This script need at least one argument to run.
-  echo Example: $0 rose-distribution-xxx.tar.gz
+  echo This script needs one argument to run.
+  echo Example: $0 ROSE_TOP_TEST_DIR 
   exit
 fi
 
-ROSE_DISTRIBUTION=$1
-ROSE_COPY=/home/liao6/rose
+# remove previous left over temporary dir generated by svn_load_dirs.??.pl
+rm -rf /tmp/svn_load_dirs*
 
-#REMOTE_SVN_REPOS=file:////home/liao6/test3/ROSE.MIRROR
-REMOTE_SVN_REPOS=https://outreach.scidac.gov/svn/rose
-echo "ROSE distribution package is:${ROSE_DISTRIBUTION}"
+ROSE_TOP_TEST_DIR=$1
+cd ${ROSE_TOP_TEST_DIR}
 
-WORK_DIR=/tmp/$$
+# find the distribution package from top/build
+ROSE_DISTRIBUTION=$(find build -name  \*source-with-EDG-binary\*.tar.gz)
+if [ $? -ne 0 ]; then
+   echo "Fatal error: cannot find the distribution package!"
+   exit 1
+fi
+echo Found the ROSE distribution package: $ROSE_DISTRIBUTION
 
-rm -rf ${WORK_DIR}
-mkdir -p ${WORK_DIR}
+ROSE_SRC=${ROSE_TOP_TEST_DIR}/sourcetree
+
+UPLOAD_DIR=${ROSE_TOP_TEST_DIR}/upload
+rm -rf ${UPLOAD_DIR}
+mkdir -p ${UPLOAD_DIR}
 
 # unpack the package to the work dir and get the root dir of the distribution
 #----------------------------------------------------
-tar xzvf ${ROSE_DISTRIBUTION} -C ${WORK_DIR}
+tar xzvf ${ROSE_DISTRIBUTION} -C ${UPLOAD_DIR}
 
-ROSE_DIST_DIR=$(ls ${WORK_DIR})
+cd ${UPLOAD_DIR}
+ROSE_DIST_DIR=$(ls ${UPLOAD_DIR})
 echo "Unpacked ROSE distribution directory is: ${ROSE_DIST_DIR}"
-
-cd ${WORK_DIR}/${ROSE_DIST_DIR}
 
 # Find all .svn directories and remove them
 #----------------------------------------------------
@@ -68,8 +80,15 @@ fi
 
 # Now we can upload the package
 #--------------------------------------------------------
-${ROSE_COPY}/scripts/svn_load_dirs.1.4.5.pl -no_user_input ${REMOTE_SVN_REPOS} trunk ${WORK_DIR}/${ROSE_DIST_DIR}
+${ROSE_SRC}/scripts/svn_load_dirs.1.4.5.pl -no_user_input ${REMOTE_SVN_REPOS} trunk ${ROSE_DIST_DIR}
+
+if [ $? -ne 0 ]; then
+   echo "Error: svn_load_dirs finishes abnormally!"
+   exit 3
+else
+  echo "svn_load_dirs.pl finishes normally."
+fi
 
 # cleanup, svn_load_dirs.pl has some trouble to clean up itself. We help it here as well
-rm -rf ${WORK_DIR}
+rm -rf ${UPLOAD_DIR}
 rm -rf /tmp/svn_load_dirs*
diff --git a/scripts/roseFreshTestBinaryDistribution b/scripts/roseFreshTestBinaryDistribution
--- a/scripts/roseFreshTestBinaryDistribution
+++ b/scripts/roseFreshTestBinaryDistribution
@@ -144,6 +144,15 @@ if [ $buildstatus == 0 ]; then
   echo "> Environment:" >> mailtext
   printenv >> mailtext
   echo "" >> mailtext
+   # Invoke the import script finally, Liao, 7/31/2008
+  ${ROSE_TOP}/sourcetree/scripts/importRoseDistributionToSVN ${ROSE_TOP}
+  if [ $? -ne 0 ]; then
+    echo "Error: importRoseDistributionToSVN finishes abnormally!" >>mailtext
+    exit 3
+  else
+    echo "importRoseDistributionToSVN finishes normally.">>mailtext
+  fi
+
 else
   echo "Subject: ROSE test $$ on `hostname` results (fail)" > mailtext
   echo "" >> mailtext
