Changed scripts to generate ChangeLog2 in the top test dir and copy it to a distribution later on. No need to commit it to the svn repository

diff --git a/scripts/importRoseDistributionToSVN b/scripts/importRoseDistributionToSVN
--- a/scripts/importRoseDistributionToSVN
+++ b/scripts/importRoseDistributionToSVN
@@ -91,6 +91,17 @@ rm -rf ${ROSE_DIST_DIR}/src/frontend/SageIII/preproc.cc
 rm -rf ${ROSE_DIST_DIR}/src/roseIndependentSupport/dot2gml/parseDotGrammar.cc
 rm -rf ${ROSE_DIST_DIR}/src/roseIndependentSupport/dot2gml/parseDot.cc
 
+# add ChangeLog2 into the distribution
+# Liao, 11/17/2009
+if test -f ${ROSE_TOP_TEST_DIR}/ChangeLog2; then
+  :
+else
+  echo "Fatal Error: ${ROSE_TOP_TEST_DIR}/ChangeLog2 does not exist as expected!" 
+  exit 1
+fi
+
+cp ${ROSE_TOP_TEST_DIR}/ChangeLog2 ${ROSE_DIST_DIR}/.
+
 # restore a few third party Makefile.in which cannot yet been automatically built
 #cp ${ROSE_SRC}/src/3rdPartyLibraries/libharu-2.1.0/script/Makefile.in ${ROSE_DIST_DIR}/src/3rdPartyLibraries/libharu-2.1.0/script/Makefile.in
 cp ${ROSE_SRC}/src/3rdPartyLibraries/libharu-2.1.0/Makefile.in ${ROSE_DIST_DIR}/src/3rdPartyLibraries/libharu-2.1.0/Makefile.in 
