Added call to build script.
git-svn-id: file:///usr/casc/overture/ROSE/svn/ROSE/trunk/ROSE@7395 a27c51de-2d2b-4d1b-a6e8-f7f87814f453

diff --git a/scripts/roseFreshTest b/scripts/roseFreshTest
--- a/scripts/roseFreshTest
+++ b/scripts/roseFreshTest
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/bash -x
 # This script does a fresh checkout of ROSE and conducts series tests
 # Please provide your customized configurations in a .sh file before using this script:
 #
@@ -166,7 +166,9 @@ buildstatus=0
           $timer $SVN ${SVNOP} -r${svnversion} -q ${ROSE_SVNROOT} $SourceTreeLocation
       else
         # default is export
-          $timer $SVN ${SVNOP} -r${svnversion} -q ${ROSE_SVNROOT} $SourceTreeLocation
+        # $timer $SVN ${SVNOP} -r${svnversion} -q ${ROSE_SVNROOT} $SourceTreeLocation
+          echo "Default is export, but make that an error for now!"
+          exit 1
       fi
   fi
 
@@ -227,16 +229,16 @@ fi
     fi
   else
   # Normal build of ROSE
-    $timer make $MAKEFLAGS || exit 1
+  # $timer make $MAKEFLAGS || exit 1
     echo "############ make done"
-    $timer make $MAKEFLAGS check || exit 1
+  # $timer make $MAKEFLAGS check || exit 1
     echo "############ make check done"
-    $timer make $MAKEFLAGS docs || exit 1
+  # $timer make $MAKEFLAGS docs || exit 1
     echo "############ make docs done"
     rmdir ../install || exit 1
-    $timer make $MAKEFLAGS install || exit 1
+  # $timer make $MAKEFLAGS install || exit 1
     echo "############ make install done"
-    $timer make $MAKEFLAGS installcheck || exit 1
+  # $timer make $MAKEFLAGS installcheck || exit 1
     echo "############ make installcheck done"
 
   # test the installed ROSE on external benchmarks, such as SPEC CPU 2006 etc.
