Fixed BOOST_ROOT warning for people who use BOOST_ROOTX rather than BOOST_ROOT
git-svn-id: file:///usr/casc/overture/ROSE/svn/ROSE/trunk/ROSE@2143 a27c51de-2d2b-4d1b-a6e8-f7f87814f453

diff --git a/scripts/roseFreshTest b/scripts/roseFreshTest
--- a/scripts/roseFreshTest
+++ b/scripts/roseFreshTest
@@ -100,7 +100,7 @@ dot -V >> mailtext1 2>&1 || echo "dot not found" >> mailtext1
 # JJW -- BOOST_ROOTX is used in my scripts because our configure scripts use
 # BOOST_ROOT as a way to find Boost so we don't really want to rely on having
 # that variable set
-(grep '#define *BOOST_LIB_VERSION' ${BOOST_ROOT}/include/*/boost/version.hpp ${BOOST_ROOTX}/include/*/boost/version.hpp | cut -f 3 -d ' ' | tr -d '"' | tr _ . | sed 's/^/Boost version: /' || echo "Boost not found") >> mailtext1
+(grep '#define *BOOST_LIB_VERSION' ${BOOST_ROOT:-$BOOST_ROOTX}/include/*/boost/version.hpp | cut -f 3 -d ' ' | tr -d '"' | tr _ . | sed 's/^/Boost version: /' || echo "Boost not found") >> mailtext1
 echo "" >> mailtext1
 echo "> Environment:" >> mailtext1
 printenv >> mailtext1
