Added clone instructions to smgit2 launcher

diff --git a/scripts/smgit2_launcher b/scripts/smgit2_launcher
--- a/scripts/smgit2_launcher
+++ b/scripts/smgit2_launcher
@@ -9,7 +9,7 @@
 ####################################################################################################################
 
 
-# Find top-level ROSE repo. These two functions are copied straight from smgit2.
+# Find top-level ROSE repo. These two functions are copied straight from smgit2 (only the "die" is modified)
 rose=$(perl -e '
     use Cwd;
     use strict;
@@ -32,20 +32,41 @@ rose=$(perl -e '
 	return $s if is_top_of_rose $s;
 	pop @comps;
       }
-      die "cannot find top of ROSE source tree (cwd=@{[getcwd]})";
+      die "smgit2_launcher: cannot find top of ROSE source tree (cwd=@{[getcwd]})\n";
     }
 
     print top_of_rose, "\n";
 ')
-[ -d "$rose" ] || exit 1
+
+if [ ! -d "$rose" ]; then
+    #     --------------------------------------------------------------------------------
+    echo "    Your current working directory is apparently not in a ROSE Git repository."
+    echo "    To start a new repository, execute these commands:"
+    echo "        git clone ROSE_REPO_URL rose"
+    echo "        cd rose"
+    echo "        git submodule init"
+    echo "        ${EDITOR-vi} .git/config # edit the URL for the EDG submodule"
+    echo "        git submodule update"
+    echo "    After you do this, this smgit2 launcher script should work."
+    echo
+    echo "    Alternatively, you can run a temporary copy of the smgit2 perl script"
+    echo "    (i.e., scripts/smgit2) found in most any existing ROSE Git repository. The"
+    echo "    command is:"
+    echo "        smgit2 clone ROSE_REPO_RUL rose"
+    #     --------------------------------------------------------------------------------
+    exit 1
+fi
 
 # Run smgit2 if possible
-rev=$(git rev-parse origin/master:scripts/smgit2)
-if [ -n "$rev" ]; then
-    echo "$0: running smgit2 revision $(echo $rev |cut -c1-8)..."
+if git rev-parse origin/master:scripts/smgit2 >/dev/null 2>&1; then
+    echo "smgit2_launcher: running smgit2 from origin/master..."
     exec perl <(git show origin/master:scripts/smgit2) "$@"
     exit 1
+elif [ -f "$rose/scripts/smgit2" ]; then
+    echo "smgit2_launcher: running $rose/scripts/smgit2..."
+    exec $rose/scripts/smgit2 "$@"
+    exit 1
 else
-    echo "$0: cannot find the real smgit2 perl script" >&2
+    echo "smgit2_launcher: cannot find the real smgit2 perl script" >&2
     exit 1
 fi
