(Testing Support) Update status passing in test scripts
Updated status passing in:
when_changed_run
utility_functions.sh
srun_do
run_and_log

Removed softlink do_srun

Changed do_rose.sh to call set_ROSE_HOME In run directory, not do_sose.sh's directory

ROSE-1946

diff --git a/scripts/lc/bin/when_changed_run b/scripts/lc/bin/when_changed_run
--- a/scripts/lc/bin/when_changed_run
+++ b/scripts/lc/bin/when_changed_run
@@ -36,6 +36,8 @@ get_file_time
 last_file_time=${file_time}
 log_waiting
 
+# Want to keep looping even if the command fails:
+set +o errexit
 while true; do
   get_file_time
   if [[ "${file_time}" != "$last_file_time" ]]; then
