shape analyses: re-activated alias annotation, graph conversion performed only when necessary, SRW->NNH conversion with every edge possibly null (correct, but superhuge graphsets)
darcs-hash:20090415110739-2b598-e92d53f1aaa754b05268723c7cfefbad111ed5a5.gz

diff --git a/projects/SATIrE/src/experimental/specs/shape2/analyze b/projects/SATIrE/src/experimental/specs/shape2/analyze
--- a/projects/SATIrE/src/experimental/specs/shape2/analyze
+++ b/projects/SATIrE/src/experimental/specs/shape2/analyze
@@ -22,12 +22,20 @@ function analyse {
   label=srw98
   echo "$binary" | grep nnh99 > /dev/null 2>&1 && label=nnh99
 
-  echo 
-  echo "**** $label *********************************************************************"
-  cmd="$binary --output-gdl=$gdlfile $OPTIONS $INPUT"
-  echo $cmd
-  $cmd || echo "-- ABORT --"
-  echo '********************************************************************************'
+  if [ -e "$binary" ]; then
+    echo 
+    echo "**** $label *********************************************************************"
+    cmd="$binary --output-gdl=$gdlfile $OPTIONS $INPUT"
+    echo $cmd
+    $cmd || echo "-- ABORT --"
+    echo '********************************************************************************'
+  else
+    echo
+    echo "$binary not found. run"
+    echo "  make $label"
+    echo "to build it."
+    echo
+  fi
 }
 
 INPUT=$1
