Added preliminary support for combining PAG analyses.
darcs-hash:20080404120743-d8bd4-a70e7b45e12f84c49f3521dc4b1ae408167f84ff.gz

diff --git a/projects/SATIrE/src/analyzer/skeletons/newanalysis.in b/projects/SATIrE/src/analyzer/skeletons/newanalysis.in
--- a/projects/SATIrE/src/analyzer/skeletons/newanalysis.in
+++ b/projects/SATIrE/src/analyzer/skeletons/newanalysis.in
@@ -10,12 +10,18 @@
 # set -x
 
 # Command line options
-while getopts ":u" Option
+while getopts ":d:p:u" Option
 do
   case $Option in
+    d) echo "Analysis depends on analyses $OPTARG"; OTHERANALYSES=$OPTARG ;;
+    p) echo "Will set prefix '$OPTARG'"; PREFIX=$OPTARG ;;
     u) echo "Will not overwrite modified files"; UPDATE="T" ;;
-    *) echo "usage: newanalysis [-uh] [analysis name] [analysis carrier type]"
-       echo "       -u : existing files are not overwritten."
+    *) echo "usage: newanalysis [OPTION]... [analysis name] [analysis carrier type]"
+       echo "supported options are:"
+       echo " -d names  : analysis depends on named analyses [not for human use]"
+       echo " -h        : this usage information"
+       echo " -p prefix : add specified prefix to analyzer function names"
+       echo " -u        : existing files are not overwritten"
        exit 1 ;;
   esac
 done
@@ -29,7 +35,7 @@ then
     ANALYSIS_NAME=`basename $CURRENTDIR`
 else
     ANALYSIS_DIR=$1
-    ANALYSIS_NAME=$1
+    ANALYSIS_NAME=`basename $1`
 fi
 
 SATIRE_DATA="@pkgdatadir@"
@@ -54,6 +60,34 @@ echo "copying files..."
 cp $SATIRE_DATA/main-support.h-template $ANALYSIS_DIR/main-support.h
 cp $SATIRE_DATA/main-support.C-template $ANALYSIS_DIR/main-support.C
 echo
+
+# generate runOtherAnalyses function
+for analysis in $OTHERANALYSES
+do
+    echo "extern \"C\" void *${analysis}_doit(void *);" >> $ANALYSIS_DIR/main-support.C
+    echo "extern \"C\" void ${analysis}_persistent(void);" >> $ANALYSIS_DIR/main-support.C
+done
+if [ "x$OTHERANALYSES" != x ]
+then
+  # add a blank line for prettiness
+    echo "" >> $ANALYSIS_DIR/main-support.C
+fi
+echo "void runOtherAnalyses(void *cfg)" >> $ANALYSIS_DIR/main-support.C
+echo "{" >> $ANALYSIS_DIR/main-support.C
+if [ "x$OTHERANALYSES" != x ]
+then
+    echo "    TimingPerformance others(\"Other data-flow analyses:\");" >> $ANALYSIS_DIR/main-support.C
+    echo "    TimingPerformance *timer;" >> $ANALYSIS_DIR/main-support.C
+fi
+for analysis in $OTHERANALYSES
+do
+    echo "" >> $ANALYSIS_DIR/main-support.C
+    echo "    timer = new TimingPerformance(\"Data-flow analysis $analysis:\");" >> $ANALYSIS_DIR/main-support.C
+    echo "    ${analysis}_doit(cfg);" >> $ANALYSIS_DIR/main-support.C
+    echo "    ${analysis}_persistent();" >> $ANALYSIS_DIR/main-support.C
+    echo "    delete timer;" >> $ANALYSIS_DIR/main-support.C
+done
+echo "}" >> $ANALYSIS_DIR/main-support.C
 
 if [ x$UPDATE = xT ]
 then
@@ -85,21 +119,39 @@ fi
 
 if [ -e "$ANALYSIS_DIR/${ANALYSIS_NAME}.set" ]
 then
-  echo "$ANALYSIS_DIR/$ANALYSIS_NAME.set exists and remains in $ANALYSIS_DIR."
+    echo "$ANALYSIS_DIR/$ANALYSIS_NAME.set exists and remains in $ANALYSIS_DIR."
 else
- echo "You must create $ANALYSIS_DIR/$ANALYSIS_NAME.set before you can compile the analyzer $ANALYSIS_DIR/$ANALYSIS_NAME."
+    echo "You must create $ANALYSIS_DIR/$ANALYSIS_NAME.set before you can compile the analyzer $ANALYSIS_DIR/$ANALYSIS_NAME."
 fi
 
 if [ -e "$ANALYSIS_DIR/$ANALYSIS_NAME.optla" ]
 then
- echo "$ANALYSIS_DIR/$ANALYSIS_NAME.optla exists and remains in $ANALYSIS_DIR."
- echo "customizing Makefile..."
- echo "ANALYSIS = $ANALYSIS_NAME" > $ANALYSIS_DIR/Makefile
- CARRIER_TYPE=`egrep 'carrier[ ]*:' $ANALYSIS_DIR/$ANALYSIS_NAME.optla | awk --field-separator ':' '{ print $2 }' | sed 's/ //g'`
- echo "CARRIER_TYPE = $CARRIER_TYPE" >> $ANALYSIS_DIR/Makefile
- cat $SATIRE_DATA/Makefile-template >> $ANALYSIS_DIR/Makefile
+    echo "$ANALYSIS_DIR/$ANALYSIS_NAME.optla exists and remains in $ANALYSIS_DIR."
+    echo "customizing Makefile..."
+    echo "ANALYSIS = $ANALYSIS_NAME" > $ANALYSIS_DIR/Makefile
+    CARRIER_TYPE=`egrep 'carrier[ ]*:' $ANALYSIS_DIR/$ANALYSIS_NAME.optla | awk --field-separator ':' '{ print $2 }' | sed 's/ //g'`
+    echo "CARRIER_TYPE = $CARRIER_TYPE" >> $ANALYSIS_DIR/Makefile
+    echo "PREFIX = $PREFIX" >> $ANALYSIS_DIR/Makefile
+    if [ x$PREFIX != x ]
+    then
+        egrep -q "prefix[ ]*:[ ]*$PREFIX" $ANALYSIS_DIR/$ANALYSIS_NAME.optla
+        if [ $? -ne 0 ]
+        then
+            echo "Warning: You must add 'prefix: $PREFIX' to $ANALYSIS_DIR/$ANALYSIS_NAME.optla."
+        fi
+        echo "PREFIX_SET = 1" >> $ANALYSIS_DIR/Makefile
+    else
+        egrep -q "prefix[ ]*:[ ]*$PREFIX" $ANALYSIS_DIR/$ANALYSIS_NAME.optla
+        if [ $? -eq 0 ]
+        then
+            echo "*** Error: $ANALYSIS_DIR/$ANALYSIS_NAME.optla sets a prefix, you must use the -p option!"
+            exit 1
+        fi
+        echo "PREFIX_SET = 0" >> $ANALYSIS_DIR/Makefile
+    fi
+    cat $SATIRE_DATA/Makefile-template >> $ANALYSIS_DIR/Makefile
 else
- echo "You must create $ANALYSIS_DIR/$ANALYSIS_NAME.optla before you can compile the analyzer $ANALYSIS_DIR/$ANALYSIS_NAME."
+    echo "You must create $ANALYSIS_DIR/$ANALYSIS_NAME.optla before you can compile the analyzer $ANALYSIS_DIR/$ANALYSIS_NAME."
 fi
 echo
 echo "All done, have fun."
