Made SATIRE_BATCH_TESTING flag useful.
darcs-hash:20080715104843-d8bd4-04f7bddf7ede06316ab6be4c55b1ab1b9342b9a7.gz

diff --git a/projects/SATIrE/src/analyzer/skeletons/runtests-template b/projects/SATIrE/src/analyzer/skeletons/runtests-template
--- a/projects/SATIrE/src/analyzer/skeletons/runtests-template
+++ b/projects/SATIrE/src/analyzer/skeletons/runtests-template
@@ -194,9 +194,16 @@ rm -f $AWKFILE
 echo
 echo "########################################################################"
 
-if [ "$BAD" != "0" && x$SATIRE_BATCH_TESTING != xtrue ]; then
-    echo "Press <Ctrl-C> to abort or <Return> to continue"
-    read
+if [ "$BAD" != "0" ]; then
+  # GB (2008-07-15): Added the use of this environment variable to make sure
+  # that we can run noninteractive tests.
+    if [ x$SATIRE_BATCH_TESTING != xtrue ]; then
+        echo "Press <Ctrl-C> to abort or <Return> to continue"
+        read
+    else
+      # There is a problem, and we are running batch tests: die!
+        exit 1
+    fi
 fi
 
 # vim: ts=4 sts=4 sw=4:
